\documentclass[preprint, 3p,
authoryear]{elsarticle} %review=doublespace preprint=single 5p=2 column
%%% Begin My package additions %%%%%%%%%%%%%%%%%%%

\usepackage[hyphens]{url}

  \journal{Transport Geography?} % Sets Journal name

\usepackage{graphicx}
%%%%%%%%%%%%%%%% end my additions to header

\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
% TODO: Currently lineno needs to be loaded after amsmath because of conflict
% https://github.com/latex-lineno/lineno/issues/5
\usepackage{lineno} % add
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \usepackage{fontspec}
  \ifxetex
    \usepackage{xltxtra,xunicode}
  \fi
  \defaultfontfeatures{Mapping=tex-text,Scale=MatchLowercase}
  \newcommand{\euro}{€}
\fi
% use microtype if available
\IfFileExists{microtype.sty}{\usepackage{microtype}}{}
\usepackage[]{natbib}
\bibliographystyle{plainnat}

\usepackage{graphicx}
\ifxetex
  \usepackage[setpagesize=false, % page size defined by xetex
              unicode=false, % unicode breaks when used with xetex
              xetex]{hyperref}
\else
  \usepackage[unicode=true]{hyperref}
\fi
\hypersetup{breaklinks=true,
            bookmarks=true,
            pdfauthor={},
            pdftitle={Leveraging GTFS to explore spatial gaps in transit supply with respect to social needs},
            colorlinks=false,
            urlcolor=blue,
            linkcolor=magenta,
            pdfborder={0 0 0}}

\setcounter{secnumdepth}{5}
% Pandoc toggle for numbering sections (defaults to be off)


% tightlist command for lists without linebreak
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}




\usepackage{subfig}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}



\begin{document}


\begin{frontmatter}

  \title{Leveraging GTFS to explore spatial gaps in transit supply with
respect to social needs}
    \author[Public Transport Research Group (PTRG)]{James Reynolds%
  %
  \fnref{1}}
   \ead{james.reynolds@monash.edu} 
    \author[Public Transport Research Group (PTRG)]{Graham Currie%
  \corref{cor1}%
  \fnref{2}}
   \ead{graham.currie@monash.edu} 
    \author[Public Transport Research Group (PTRG)]{Yanda Qu%
  %
  \fnref{3}}
   \ead{yanda.qu@monash.edu} 
      \affiliation[Public Transport Research Group (PTRG)]{
    organization={Public Transport Research Group (PTRG), Institute of
Transport Studies, Department of Civil Engineering Engineering, Monash
University},addressline={Clayton
Campus},city={Melbourne},postcode={3800},state={Victoria},country={Australia},}
    \cortext[cor1]{Corresponding author}
    \fntext[1]{Research Fellow}
    \fntext[2]{Professor}
    \fntext[3]{PhD Student}
  
  \begin{abstract}
  This is the abstract.

  It consists of two paragraphs.
  \end{abstract}
    \begin{keyword}
    keyword1 \sep 
    keyword2
  \end{keyword}
  
 \end{frontmatter}

\section{Introduction}\label{introduction}

A need to provide at least some motorised mobility for those who cannot
otherwise drive themselves influences transit service levels in many
places \citep{Currie:2016aa}. Age, disability, socio-economic status,
lack of a driver's license or vehicle, and many other factors might make
someone reliant on transit services for some or all of their travel.
Social-equity perspectives on transport policy-making, especially the
desire to improve vertical equity so as to better support those who are
disadvantaged (c.f. \citet{Litman:2016aa}), might therefore suggest
providing at least some transit, and probably more than just a minimum,
to places that have the highest social need for transport.

\citet{Currie2003Hobart}, \citet{Currie2004Gap},
\citet{Currie2007Identifying} and \citet{currie2010identifying}
developed an approach for identifying spatial gaps in transit supply
related to social needs for transport. This involves identifying areas
with very high needs for transport, yet little or no service, and was
applied to a case study of 2006 transit service levels in Greater
Melbourne, Australia. However, there does not appear to have been much
further use or development of this approach. As well, it is unclear if
the spatial patterns identified in this previous research, are
representative of transit supply and social needs in other places, or
whether the location of gaps in Melbourne itself have changed in the
intervening years. This may in part be because until recently transit
schedule data was not readily available in consistent, electronic
formats, meaning that assessing transit supply was a large task.

Nowadays, more than 10,000 transit agencies publicly release timetable
data in the General Transit Feed Specification (GTFS) format
\citep{GTFS}. Such standardisation allows Google Maps and other online
platforms to provide outputs for any place with a GTFS feed, and has
facilitated research and other analysis of transit services. However,
tools for using GTFS data to examine spatial patterns and gaps in
transit supply with respect to social needs for transport do not appear
to be readily available. This gap, and the lack of direct follow up to
\citet{Currie2003Hobart}, \citet{Currie2004Gap},
\citet{Currie2007Identifying} and \citet{currie2010identifying}, provide
the motivation for this paper.

The three main objectives of this research are: (1) to develop tools for
undertaking needs-gap analysis using GTFS datasets; (2) to explore
whether such gaps in Melbourne have changed since the publication of
\citet{Currie2007Identifying} and \citet{currie2010identifying}; and (3)
to better understand whether spatial patterns in Melbourne are
representative of those in other places. Research outcomes that are
reported in this paper include the development of a new R package
(gtfssupplyindex) with software tools that facilitate the use of the
\citet{Currie2003Hobart}, \citet{Currie2004Gap},
\citet{Currie2007Identifying} and \citet{currie2010identifying}
approach, in particular the calculation of transit Supply Index (SI)
scores from GTFS datasets. Also presented in this paper are results for
Australian cities in 2016 and 2021, matching the most recent censuses,
which are compared across locations and to the 2006 analysis of
Melbourne reported in \citet{currie2010identifying}.

The remainder of this paper is structured as follows: the next section
outlines the background to this research. Section 3 describes the study
methodology, followed by presentation of results in Section 4 and
discussion in Section 5. Limitations of this study, directions for
future research and a brief conclusion are provided in Section 6.

\section{Research context}\label{research-context}

\subsection{Transit metrics}\label{transit-metrics}

There are many metrics available for benchmarking transit services.
These include those in the Transit Cooperative Research Program (TCRP)
Report 88, a guidebook for developing performance-measurement systems
\citep{Ryus:2003aa}; and those used across benchmarking databases and
programs such as \citet{Florida-Transit-Information-System:2018aa},
\citet{UITP:2015aa} and \citet{Imperial-College-London:2023aa}. The
Fielding Triangle \citep{FieldingGordonJ1987Mpts} provides a framework
for combining indicators of service inputs, outputs and consumption to
describe cost efficiency, cost effectiveness and service effectiveness.
More broadly: \citet{Litman:2003ab} and \citet{Litman:2016aa} discuss
some of the traffic, mobility, accessibility, social equity, strategic
planning and other rational decision-making-based perspectives
underlying many transport indicators; \citet{Reynolds:2017ah} extends
these into models of how institutionalism, incrementalism and other
public policy analysis concepts might apply to decision-making processes
relating to transit prioritization; \citet{GuzmanLuisA.2017Aeit}
developed a measure of accessibility in the context of policy
development and social equity for Latin American Bus Rapid Transit (BRT)
networks; and \citet{Creutzig2020streetspaceallocation} introduced
street space allocation metrics based around ten ethical principles.

However, many of these metrics may be difficult to calculate, explain or
understand, especially for those who are not planners, engineers or
other technical specialists. Where pre-calculated transit metrics are
immediately available, such as on a website or other online platform, it
may not be possible to independently generate scores, for instance to
assess proposed system changes. Contrasting examples are provided by:

\begin{itemize}
\item
  Transit Scores \citep{WalkScore:2023tg}, which are readily available
  online for locations with a published GTFS feed. The meaning of the
  metric appears easy to explain, with the highest possible score of 100
  representing the sort of transit accessibility experienced in the
  center of New York. However, the Transit Score algorithm is secret,
  and scores cannot be calculated independently or generated for
  proposed changes to networks.
\item
  The Transit Capacity and Quality of Service Manual (TCQSM), which
  provides a wide range of metrics for measuring different aspects of a
  transit system. The TCQSM scores themselves appear easy to understand
  or explain, ranging from A (good) to F (bad), although the large
  number of metrics might be somewhat overwhelming for some users. The
  scores, however, can be calculated independently, given sufficient
  data.
\end{itemize}

The widespread availability of GTFS datasets in recent years has
facilitated the development of tools, such as the Transit Score, that
apply the same metric to many transit systems. \citet{Wong:2013aa}
provides an example of what can be done with GTFS data, open metrics and
coding, by reporting the distribution of various TCQSM metrics across 50
USA transit operators. Code used in the \citet{Wong:2013aa} analysis is
available for those who might wish to produce a similar study for other
locations and systems. Developing a similar code base, but for
calculating metrics associated with spatial gaps in transit supply based
on social needs, is the subject of this paper.

\subsection{The Transit Suppy Index}\label{the-transit-suppy-index}

An objective of this study is to produce code that facilitates
calculation of the SI metric from GTFS data. A generalized form of the
SI equation, adapted from \citet{currie2010identifying}, is:

\[SI_{area, time} = \sum{\frac{Area_{Bn}}{Area_{area}}SL_{n, time}}\]

where:

\begin{itemize}
\item
  \(SI_{area, time}\) is the Supply Index for the area of interest and a
  given period of time;
\item
  \(Area_{Bn}\) is the buffer area for each stop (n) within the area of
  interest (in \citet{currie2010identifying} this was based on a radius
  of 400 metres for bus and tram stops, and 800 metres for railway
  stations);
\item
  \(Area_{area}\) is the area of the area of interest; and
\item
  \(SL_{n,time}\) is the number of transit arrivals for each stop for a
  given time period.
\end{itemize}

\begin{figure}
\includegraphics[width=1\linewidth]{graphics/Currie2010SI} \caption{Distribution of supply measure scores – Metropolitan Melbourne (2006), Source: Currie (2010)}\label{fig:Currie_map_SI}
\end{figure}

\citet{currie2010identifying} reported SI scores for Census Collection
Districts (CCDs) across Metropolitan Melbourne in 2006, as shown in
Figure \ref{fig:Currie_map_SI}. General patterns were identified, being:
more transit supply in the middle and inner suburbs, and along passenger
railway lines; and outer areas tending to have very low SI scores or no
transit supply at all.

\subsection{Social need and needs-gap}\label{social-need-and-needs-gap}

As well as measuring transit supply, \citet{currie2010identifying}
assessed the social need for transport across Metropolitan Melbourne
using: the Australian Bureaus of Statistics' Index of Related
Socio-Economic Advantage/Disadvantage (IRSAD) and a transport needs
index derived from eight weighted indicators. The spatial distribution
of this composite social needs index in 2006, reproduced in Figure
\textbackslash ref\{fig:Currie\_map\_needs), showed that areas of above
average, high and very high social needs in 2006 were located in: some
outer areas, particularly in the east and south-east; and in some middle
areas in the south-east, north and west.

\begin{figure}
\includegraphics[width=1\linewidth]{graphics/Currie2010Needs} \caption{Distribution of categories of composite social need index scores - Metropolitan Melbourne (2006). Source: Currie (2010.)}\label{fig:Currie_map_needs}
\end{figure}

As the final step in the spatial needs-gap analysis,
\citet{currie2010identifying} identified areas with very high transport
needs, but very low or no transit supply, as reproduced in Figure
\ref{fig:Currie_map_gap}. These areas were identified as being those
where service gaps might be of particular concern. Most of these were
located in outer parts of Melbourne in the north-east, south-east and
south, although there were also some pockets in the middle suburbs in
the west, north and south east. Overall, \citet{currie2010identifying}
found that ``8.2\% of Melbourne residents have `very high' needs but
`zero', `low' or `very low' public transport supply.''

\begin{figure}
\includegraphics[width=1\linewidth]{graphics/Currie2010gap} \caption{Distribution of CCDs with very high transport needs and with zero or very low public transport supply - Metropolitan Melbourne (2006). Source: Currie (2010)}\label{fig:Currie_map_gap}
\end{figure}

Using this methodology in transit planning was suggested as
``substantially more useful than the presentation of anecdotal evidence,
which is the most common means of identifying transport needs in local
transport studies throughout the world''\citep{currie2010identifying}.
However, it does not appear that this approach has been widely adopted
in practice or by researchers. Our suspicion is that while the SI has a
relatively simple formula and requires only geographic and timetable
data to calculate, a lack of software tools may be partly why it has not
been more widely adopted.

It is also unclear whether the patterns in Melbourne identified in
\citet{currie2010identifying} have changed since the 2006 analysis, or
if Melbourne is representative of other locations. Developing a software
tool to calculate SI tools from GTFS data, and then using it to
comparing current conditions and other locations to the findings of
\citet{currie2010identifying}, therefore, provides the motivation for
this research.

\section{Methodology}\label{methodology}

\subsection{Code development}\label{code-development}

This study developed a package of tools for calculating the SI from GTFS
data using the R programming language \citep{R-base}. The
recommendations of \citet{wickham2023r} informed the package setup and
development approach. Various existing packages and code examples were
relied upon including: the sf package \citep{R-sf} for geospatial
analysis; the tidyverse \citep{tidyverse2019}; gtfstools
\citep{R-gtfstools}; and tidytransit \citep{R-tidytransit}. Australian
Bureau of Statistics (ABS) data was also used, sourced via the strayr
and absmapsdata packages \citep{r-strayr}.

Code was developed and tested on the Mornington Peninsula Tourist
Railway GTFS feed. This was selected primarily for convenience, given
that the authors are familiar with the surrounding geography and that
the feed covers a small number of trips across just three stations.

\subsection{Changes since 2006 in
Melbourne}\label{changes-since-2006-in-melbourne}

Much has changed since 2006, including the spatial geography used by the
Australian Bureau of Statistics (ABS) to collect census data. To allow
direct comparison between 2006 and the most recent census, therefore,
this study calculated SI scores using the same Census Collection
Districts (CCDs) used by \citet{currie2010identifying} for the week
starting the day of the 2021 census. The Victorian GTFS feed, published
by Public Transport Victoria (PTV), was used with historical feeds
sourced via \citet{transitfeeds_victoria:2023aa}.

Unfortunately, it is not possible to obtain 2016 or 2021 social
disadvantage data for CCDs, as the ABS no longer releases data using
this geographic scheme. Instead, population and other statistics are now
released for Statistical Area 1 (SA1) zones, which have been adopted as
the areas-of-interest in this study.

\subsection{Variation in spatial patterns across location and
time.}\label{variation-in-spatial-patterns-across-location-and-time.}

SI scores were also calculated for other capital cities in Australia,
for the weeks starting on the days of the 2016 and 2021 censuses.
Historical GTFS data was again sourced via the Transit Feeds website.
Unfortunately it was not possible to locate 2021 GTFS data for Greater
Sydney or Greater Darwin, so SI scores were calculated for 2024 using
the latest data sets, sourced directly from the relevant transit
authorities.

\subsection{Measuring social
disadvantage}\label{measuring-social-disadvantage}

This study adopts a similar approach to measuring social disadvantage as
used in \citet{currie2010identifying}, using: the ABS' Index of Relative
Socio-Economic Advantage/Disadvantage (IRSAD); and a transport needs
index\footnote{The same need indicators and weightings used in
  \citet{currie2010identifying} were adopted, although \$799 or lower
  per week was used as the threshold for low income households rather
  than \$499 to account for inflation (as per the Reserve Bank of
  Australia's online inflation calculator).}. A composite needs
indicator was derived based on the IRSAD and the transport needs index,
again as per the \citet{currie2010identifying} approach. However,
changes to the ABS reporting systems mean that the composite needs
indicator had to be based on weighting both the IRSAD index and the
transport need index by the total population of each SA1 zone, which
were then added, standardised and split into six groups\footnote{This
  contrasts to the method used by \citet{currie2010identifying}, where
  the composite needs index also included relative need components,
  being the IRSAD and the transport needs indexes weighted by the
  population within the various needs groups in each area of interest
  (for a total of four indicators included in the composite needs
  indicator, compared to only two in the 2016 and 2021 results presented
  here.}.

\section{Results}\label{results}

\subsection{The gtfssupplyindex
Package}\label{the-gtfssupplyindex-package}

Code developed to calculate SI scores is available as an R package on
github (see \citet{gtfssupplyindex_github}). Included in the package is
a vignette (INCLUDE LINK) that outlines the structure of the
calculations, the developed functions. Also included in the vignette are
step-by-step calculations for the Mornington Peninsula Railway as a
worked example, and comparison to SI scores calculated manually.

\subsection{Melbourne in 2021: changes since
2006}\label{melbourne-in-2021-changes-since-2006}

\subsubsection{Transport Supply
Categories}\label{transport-supply-categories}

\begin{figure}
\includegraphics[width=1\linewidth]{Leveraging_GTFS_to_assess_transit_supply_Transport_Geography_files/figure-latex/Greater_Melbourne_CCD_2021-1} \caption{Greater Melbourne (2006 extents), Transport Supply by CCD, week starting the day of the 2021 census}\label{fig:Greater_Melbourne_CCD_2021}
\end{figure}

Figure \ref{fig:Greater_Melbourne_CCD_2021} shows the distribution of
Transport Supply categories\footnote{The same Transport Supply
  categorizations have been used as in \citet{currie2010identifying},
  with those CCDs that have above average SI scores split evenly into
  three groups, those that have below average SIs also split evenly into
  three groups, and those CCDs without SI scores of zero placed in their
  own category. Hence, both Figure \ref{fig:Currie_map_SI} and Figure
  \ref{fig:Greater_Melbourne_CCD_2021} show relative service levels in
  each CCD compared to the rest of Greater Melbourne for that year.}
across Melbourne in the week of the 2021 census, using the same (2006)
CCD boundaries\footnote{Note, however, that there are some
  inconsistencies in the CCDs included in Metropolitan Melbourne in
  \citet{currie2010identifying} (5,839) and the number included in ABS
  dataset used for this analysis (6,325).} as in Figure
\ref{fig:Currie_map_SI}. The overall spatial patterns appear generally
similar in 2021 as they were in 2006, with higher levels of transit
supply in inner areas and close to most railway lines. However, there
are some clear differences, including:

\begin{itemize}
\tightlist
\item
  in the south-west (Werribee) service levels and coverage appear to
  have increased.
\item
  the 2021 map shows railway extensions to Sunbury (north-west) and
  Craigieburn (north), both of which involved electrification to
  incorporate existing line segments (already served by country
  services) into the surburban network. Transport Supply to Sunbury,
  however, appears to still be below average, suggesting that not much
  has changed following the shift from service by regional trains to
  suburban trains. For Craigieburn, in contrast, there has been
  increases in service levels, with some areas now having Above Average
  supply.
\item
  in the outer west (Melton) transport supply has fallen below average
\item
  less of the inner area appears to be covered by Very High transport
  supply, although most of this remains Above Average or High, with the
  exception of Albert Park (immediately south of the city centre) which
  has dropped below average;
\item
  some middle south-eastern suburbs along the bay (vicinty of Black
  Roack) have dropped below average;
\item
  Service levels have increased in some parts of the middle north-east
  (Doncaster and Croydon), outer-east (Berwick) and outer south-east
  (Cranbourne).
\item
  Services appear to have been introduced to some outer eastern (east of
  Gembrook), south-eastern (Koo Wee Rup, Lang Lang, Nar Nar Goon,
  Garfield, Bunyip and others) and southern (St Andrews Beach) areas.
\end{itemize}

\begin{table}

\caption{\label{tab:Greater_Melbourne_SA1_2021_table}Distribution of Transport Supply to Metropolitan Melbourne CCDs (2006, 2021),  Greater Melbourne SA1s (2021) and resident population (Metro Melbourne 2006, Greater Melbourne 2021). Sources: 2006 values, Currie (2010); 2021 values, authors analysis}
\centering
\begin{tabular}[t]{l|r|r|r|r|r}
\hline
\multicolumn{1}{c|}{Transport} & \multicolumn{2}{c|}{CCDs} & \multicolumn{1}{c|}{SA1s} & \multicolumn{2}{c}{Population} \\
\cline{1-1} \cline{2-3} \cline{4-4} \cline{5-6}
Supply & 2006 & 2021 & 2021 & 2006 & 2021\\
\hline
Zero Supply & 3.2\%   (189) & 1.3\%    (81) & 4.3\%    (489) & 2.5\%    (85,423) & 3.8\%   (186,829)\\
\hline
Very Low & 22.5\% (1,314) & 23.3\% (1,474) & 23.4\%  (2,692) & 23.6\%   (793,046) & 23.0\% (1,132,967)\\
\hline
Low & 22.4\% (1,310) & 23.3\% (1,473) & 23.4\%  (2,691) & 25.7\%   (865,330) & 23.7\% (1,163,358)\\
\hline
Below average & 22.2\% (1,294) & 23.3\% (1,473) & 23.4\%  (2,691) & 23.0\%   (774,521) & 23.6\% (1,159,783)\\
\hline
Above average & 10.4\%   (608) & 9.6\%   (608) & 8.5\%    (975) & 9.6\%   (324,546) & 8.7\%   (426,892)\\
\hline
High & 9.2\%   (535) & 9.6\%   (608) & 8.5\%    (974) & 7.7\%   (260,411) & 8.7\%   (425,779)\\
\hline
Very High & 10.1\%   (589) & 9.6\%   (608) & 8.5\%    (975) & 7.8\%   (263,832) & 8.6\%   (422,025)\\
\hline
Total & 100.0\% (5,839) & 100.0\% (6,325) & 100.0\% (11,487) & 100.0\% (3,367,109) & 100.0\% (4,917,633)\\
\hline
\end{tabular}
\end{table}

Table \ref{tab:Greater_Melbourne_SA1_2021_table} summarises the
distribution of CCDs, SA1s and resident population across different
Transport Supply categories in 2006 and 2021. The differences between
the share of CCDs in each category in 2006 and 2021 are statistically
significant (\(\chi^2(6, N = 12164) = 59.15\), \(p < .001\)), with only
81 in 2021 (1.3\%) of CCDs in Melbourne having Zero Supply in 2021,
compared to the 189 (3.2\%) reported by \citet{currie2010identifying}
for 2006.

These values, however, are for CCDs within the 2006 extents of
Melbourne. For the 2021 census the ABS adopted a statistical boundary of
``Greater Melbourne'' that includes areas up to around 30 kilometres
further to the north of the 2006 boundary. As such, the fourth column in
Table \ref{tab:Greater_Melbourne_SA1_2021_table} reports the
distribution of Transport Supply category across the 2021 extent of
Greater Melbourne, while also adopting the 2021 SA1 zones as the area of
interest. Again, the differences between 2006 (CCDs) and 2021 (SA1s) are
statistically significant (\(\chi^2(6, N = 17326) = 44.83\),
\(p < .001\)), but there are a greater proportion of SA1s with Zero
Supply in 2021 (4.3\%) than there were CCDs in 2006. The share of SA1s
with supply below the average (i.e.~Zero, Very Low, Low or Below
Average) is also larger in 2021 (74.5\%) compared to the share of CCDs
in 2006 (70.3\%).

Table \ref{tab:Greater_Melbourne_SA1_2021_table} also compares the share
of population resident within areas that have each category of Transport
Supply, with differences again being statistically significant
(\(\chi^2(6, N = 8284742) = 19038.97\), \(p < .001\)). Differences in
the share of people living in areas with Zero Supply were also
statistically significant (\(\chi^2(1, N = 8284742) = 10018.38\),
\(p < .001\), \(\phi = .03\)), increasing from the 85,423 residents
(1.7\%) in 2006 to 186,829 (3.8\%) in 2021. This represents a 118.7\%
increase, compared to the Melbourne population increase of only 46.0\%.
However, the share of people living in areas with supply that is below
the average has decreased from 74.8\% to 74.1\%, with this deifference
also being statistically significant
(\(\chi^2(1, N = 8284742) = 532.56\), \(p < .001\), \(\phi = .01\)).

\subsubsection{Supply Index scores}\label{supply-index-scores}

The average SI value has also increased to 3,390 in from the value of
2,886.9 in 2006 reported in \citet{currie2010identifying}, indicating
that the overall transit service supply score has increased by
approximately 31\%. SI scores average 12,275.7, 3,409.1 and 999 for the
inner, middle and outer suburbs respectively\footnote{The same grouping
  of LGAs to inner, middle and outer suburb groups as used in
  \citet{currie2010identifying} was used for this analysis, although
  here the City of Stonnington was allocated entirely to the middle
  grouping, whereas \citet{currie2010identifying} allocated part of this
  LGA to the inner group.}, compared to 10,922.7, 2,694.9 and 764.3,
respectively, reported for 2006 in \citet{currie2010identifying}.

\subsubsection{Social needs}\label{social-needs}

Figure \ref{fig:Greater_Melbourne_2021_social_needs} shows the
distribution of categories of social need index scores across Greater
Melbourne for 2021. This figure is analogous to the 2006 value from
\citet{currie2010identifying} shown in Figure \ref{fig:Currie_map_needs}
although, as discussed in the methodology section above, it was not
possible to exactly replicate the \citet{currie2010identifying} approach
due to changes in the way census results are reported.

\begin{figure}
\includegraphics[width=0.9\linewidth]{Leveraging_GTFS_to_assess_transit_supply_Transport_Geography_files/figure-latex/Greater_Melbourne_2021_social_needs-1} \caption{Distribution of categories of composite social need index scores, overlayed with: 2006 Greater Melbourne boundary (black); middle/outer and inner/middle suburb boundaries (grey); and suburban railway lines (dashed).}\label{fig:Greater_Melbourne_2021_social_needs}
\end{figure}

Comparing Figure \ref{fig:Greater_Melbourne_2021_social_needs} and
Figure \ref{fig:Currie_map_needs} suggests that in 2021, compared to
2006:

\begin{itemize}
\tightlist
\item
  the spatial grouping of different levels of social need is less
  consistent, although this may be an artefact of the shift to SA1s from
  CCDs\footnote{CCDs were originally devised to group the approximately
    200 dwellings allocated to each individual census collector, whereas
    SA1s were introduced in be consistent in population (200 to 800
    people, averaging 400) and character\citep{ABS_SA1s_CCDs}}.;
\item
  Lower relative social needs through some parts of the middle northern
  suburbs (around Fawkner and Thornbury), and in the south-east (around
  Dandenong and Lang Lang)
\item
  higher relative needs in some areas of the south-west (around
  Werribee), the northeast (HUrstbridge, Plenty, Bundoora and
  surrounds); and the east (near Gembrook, Maryknoll, and some areas
  around Officer, Beaconsfield and Carrum Downs).
\end{itemize}

\subsubsection{Needs-gap analysis}\label{needs-gap-analysis}

\begin{table}

\caption{\label{tab:Greater_Melbourne_2021_needs_gap_zones}Greater Melbourne 2021, SA1s within each SI and Combined Needs Index grouping}
\centering
\fontsize{7}{9}\selectfont
\begin{tabular}[t]{l|r|r|r|r|r|r|r}
\hline
\multicolumn{1}{c|}{ } & \multicolumn{6}{c|}{Combined Needs Index Category} & \multicolumn{1}{c}{ } \\
\cline{2-7}
Supply & Very High & High & Above Average & Below Average & Low & Very Low & Total\\
\hline
Zero Supply & 0.5\%    (61) & 0.5\%    (51) & 0.4\%    (49) & 0.7\%    (79) & 0.9\%    (95) & 1.2\%   (130) & 4.2\%    (465)\\
\hline
Very Low & 3.7\%   (408) & 3.3\%   (369) & 3.2\%   (353) & 4.0\%   (442) & 4.1\%   (454) & 4.7\%   (520) & 22.9\%  (2,546)\\
\hline
Low & 3.1\%   (346) & 3.4\%   (376) & 3.6\%   (404) & 4.5\%   (500) & 4.6\%   (514) & 4.3\%   (478) & 23.5\%  (2,618)\\
\hline
Below average & 3.1\%   (350) & 3.7\%   (413) & 3.9\%   (430) & 4.4\%   (487) & 4.3\%   (481) & 4.3\%   (483) & 23.7\%  (2,644)\\
\hline
Above average & 1.4\%   (155) & 1.4\%   (152) & 1.4\%   (156) & 1.7\%   (188) & 1.5\%   (165) & 1.3\%   (140) & 8.6\%    (956)\\
\hline
High & 1.5\%   (165) & 1.5\%   (162) & 1.4\%   (154) & 1.7\%   (194) & 1.4\%   (161) & 1.1\%   (120) & 8.6\%    (956)\\
\hline
Very High & 1.7\%   (194) & 1.4\%   (155) & 1.2\%   (133) & 1.3\%   (144) & 1.5\%   (164) & 1.5\%   (163) & 8.6\%    (953)\\
\hline
Total & 15.1\% (1,679) & 15.1\% (1,678) & 15.1\% (1,679) & 18.3\% (2,034) & 18.3\% (2,034) & 18.3\% (2,034) & 100.0\% (11,138)\\
\hline
\end{tabular}
\end{table}

There is a significant, but only weakly positive correlation between the
2021 SI and Combined Needs Index scores (\(r(11136) = .06\),
\(p < .001\)). Table \ref{tab:Greater_Melbourne_2021_needs_gap_zones}
compares the Transport Supply and Composite Needs groupings for 2021.
Differences in the share of groupings across categories is statistically
significant (\(\chi^2(30, N = 11138) = 133.16\), \(p < .001\)), with
more of the SA1s with higher needs tending to have transport supplies
that are higher than the average. 469 SA1s have Zero or Very Low
transport supply, but very high social needs. This represents 4.2\% of
the 11,138 SA1s within Greater Melbourne, and is a lower proportion than
that reported for 2006 (279 of 5,720 CCDs (4.9\%)) in
\citet{currie2010identifying}.

\begin{table}

\caption{\label{tab:Greater_Melbourne_2021_needs_gap_population}Greater Melbourne 2021, Population in each SI and Combined Needs Index grouping}
\centering
\fontsize{6}{8}\selectfont
\begin{tabular}[t]{l|r|r|r|l|r|r|r}
\hline
\multicolumn{1}{c|}{ } & \multicolumn{6}{c|}{Combined Needs Index Category} & \multicolumn{1}{c}{ } \\
\cline{2-7}
Supply & Very High & High & Above Average & Below Average & Low & Very Low & Total\\
\hline
Zero Supply & 0.9\%    (41,915) & 0.6\%  (27,179) & 0.5\%  (22,705) & 0.7\%  (32,328) & 0.7\%  (32,645) & 0.6\%  (30,002) & 3.8\%   (186,774)\\
\hline
Very Low & 6.0\%   (291,972) & 4.1\% (199,467) & 3.4\% (166,490) & 3.7\% (181,719) & 3.2\% (158,919) & 2.6\% (129,294) & 23.0\% (1,127,861)\\
\hline
Low & 4.9\%   (239,267) & 4.2\% (205,397) & 3.9\% (193,642) & 4.3\% (210,538) & 3.7\% (183,274) & 2.7\% (130,477) & 23.7\% (1,162,595)\\
\hline
Below average & 4.7\%   (229,221) & 4.5\% (219,755) & 4.2\% (203,985) & 4.1\% (203,230) & 3.5\% (171,561) & 2.7\% (130,322) & 23.6\% (1,158,074)\\
\hline
Above average & 2.1\%   (100,957) & 1.6\%  (80,380) & 1.5\%  (73,062) & 1.6\%  (76,179) & 1.2\%  (56,902) & 0.8\%  (37,419) & 8.7\%   (424,899)\\
\hline
High & 2.2\%   (107,121) & 1.7\%  (83,970) & 1.4\%  (70,132) & 1.6\%  (77,767) & 1.1\%  (54,119) & 0.7\%  (32,274) & 8.7\%   (425,383)\\
\hline
Very High & 2.6\%   (129,759) & 1.6\%  (79,306) & 1.2\%  (59,356) & 1.2\%  (56,412) & 1.1\%  (53,477) & 0.8\%  (40,417) & 8.5\%   (418,727)\\
\hline
Total & 23.2\% (1,140,212) & 18.3\% (895,454) & 16.1\% (789,372) & 17.1\% (838,173) & 14.5\% (710,897) & 10.8\% (530,205) & 100.0\% (4,904,313)\\
\hline
\end{tabular}
\end{table}

\begin{figure}
\centering
\includegraphics{Leveraging_GTFS_to_assess_transit_supply_Transport_Geography_files/figure-latex/Greater_Melbourne_2021_needs_gap_population-1.pdf}
\caption{Greater Melbourne 2021, Populations within each SI and Combined
Needs Index grouping}
\end{figure}

Table \ref{tab:Greater_Melbourne_2021_needs_gap_population} compares the
populations within each SI and Combined Needs Index grouping for 2021.
There is a statistically significant relationship
(\(\chi^2(30, N = 4904313) = 55385.24\), \(p < .001\)), with more of the
population that has higher needs tending to be living in SA1s that have
transport supplies that ave higher than the average. 333,887 people live
within SA1s that have Zero or Very Low transport supply, but Very High
social needs. This represents 6.8\% of the 4,904,313 people within
Greater Melbourne, and is higher proportion than that reported for 2006
(139,004 of 3.3 million people (4.2\%)).

\begin{figure}
\includegraphics[width=1\linewidth]{Leveraging_GTFS_to_assess_transit_supply_Transport_Geography_files/figure-latex/Greater_Melbourne_2021_needs_gap_map-1} \caption{Greater Melbourne 2021 SI groupings, overlayed with SA1s with very high transport need areas with zero or very low public transport supply (red).}\label{fig:Greater_Melbourne_2021_needs_gap_map}
\end{figure}

Figure \ref{fig:Greater_Melbourne_2021_needs_gap_map} shows SA1 zones in
Greater Melbourne with Very High transport needs, but Very Low or Zero
transit supply for 2021. Comparison to the 2006 spatial distribution
shown in Figure \ref{fig:Currie_map_gap} suggests that:

\begin{itemize}
\tightlist
\item
  areas of the outer west (south west of Sunshine), middle north
  (Broadmeadows), the north-east (Healesville, Powelltown, Yarra
  Junction, Warburton) and the south east (Bunyip, Garfield, Koo Wee
  Rup, Lang Lang) no longer have as large a gap between the social need
  for transport and the level of transit supplied;
\item
  some on the Mornington Penninsula still have gaps, including around
  Stoney Point, Portsa, Blairgowrie and St Andrews Beach; and
\item
  there are many areas, mostly in outer surburbs, that now have large
  gaps between the social need for transport and the level of transit
  provided.
\end{itemize}

\subsection{Greater Melbourne: 2016 and
2021}\label{greater-melbourne-2016-and-2021}

\subsubsection{Transport Supply
Categories}\label{transport-supply-categories-1}

\begin{figure}
\centering
\includegraphics{Leveraging_GTFS_to_assess_transit_supply_Transport_Geography_files/figure-latex/Greater_Melbourne_2016_2021_plot-1.pdf}
\caption{Greater Melbourne, Transit Supply by 2021 SA1 for the weeks
starting the date of 2016 and 2021 census, overlayed with: 2006 Greater
Melbourne boundary (black); middle/outer and inner/middle suburb
boundaries (grey); and suburban railway lines (dashed)}
\end{figure}

Figure \ref{fig:Greater_Melbourne_2016_2021_plot} shows the distribution
of Transport Supply categories across Greater Melbourne in the week of
the 2016 and 2021 censuses, using the SA1 2021 boundaries. The overall
spatial patterns appear generally similar. Some locations that have
higher categories of transport supply in 2021 are apparent, including
around Werribee (outer south-west), Craigieburn (outer north) and
Lillydale (outer north-west).

\begin{table}

\caption{\label{tab:Greater_Melbourne_SA1_2016_2021_table_and_bar_chart}Greater Melbourne: Distribution of SA1s and resident population to Transit Supply categories, 2016 and 2021, using the 2021 SA1 boundaries}
\centering
\begin{tabular}[t]{l|r|r|r|r}
\hline
\multicolumn{1}{c|}{Transit Supply} & \multicolumn{2}{c|}{2016} & \multicolumn{2}{c}{2021} \\
\cline{1-1} \cline{2-3} \cline{4-5}
category & SA1s & Population & SA1s & Population\\
\hline
Zero Supply & 6.8\%    (780) & 3.6\%   (161,045) & 4.3\%    (489) & 3.8\%   (186,829)\\
\hline
Very Low & 22.9\%  (2,634) & 21.5\%   (966,300) & 23.4\%  (2,692) & 23.0\% (1,132,967)\\
\hline
Low & 22.9\%  (2,633) & 24.2\% (1,083,606) & 23.4\%  (2,691) & 23.7\% (1,163,358)\\
\hline
Below average & 22.9\%  (2,633) & 24.5\% (1,100,603) & 23.4\%  (2,691) & 23.6\% (1,159,783)\\
\hline
Above average & 8.1\%    (936) & 8.8\%   (395,116) & 8.5\%    (975) & 8.7\%   (426,892)\\
\hline
High & 8.1\%    (935) & 8.8\%   (392,868) & 8.5\%    (974) & 8.7\%   (425,779)\\
\hline
Very High & 8.1\%    (936) & 8.6\%   (385,683) & 8.5\%    (975) & 8.6\%   (422,025)\\
\hline
Total & 100.0\% (11,487) & 100.0\% (4,485,221) & 100.0\% (11,487) & 100.0\% (4,917,633)\\
\hline
\end{tabular}
\end{table}

Table \ref{tab:Greater_Melbourne_SA1_2016_2021_table_and_bar_chart}
compares the share of SA1s and resident population in each transport
supply category. Differences are statistically significant across the
number of SA1s (\(\chi^2(6, N = 22974) = 71.01\), \(p < .001\)) and
population share (\(\chi^2(6, N = 9402854) = 3832.57\), \(p < .001\)).
The number of SA1s with Zero or Very Low transport supply fell from
3,414 (29.7\%) to 3,181 (27.7\%), but number of people with zero supply
rose from 1,127,345 (25.1\%) to 1,319,796 (26.8\%). This represents a
17.1\% increase, compared to the population increase of 9.6\% across all
of Greater Melbourne.

\subsubsection{Supply Index scores}\label{supply-index-scores-1}

\begin{figure}
\centering
\includegraphics{Leveraging_GTFS_to_assess_transit_supply_Transport_Geography_files/figure-latex/Greater_Melbourne_2016_2021_scatterplot_SA12021-1.pdf}
\caption{Greater Melbourne: SI scores in 2016 and 2021 by SA1 (2021
boundaries), adjusted to set those \textless1 equal to 1 (for visual
clarity)}
\end{figure}

\begin{table}

\caption{\label{tab:Greater_Melbourne_2016_2021_ratio_table}Greater Melbourne: hanges in SI score between 2016 and 2021 (column 1) by number of SA1 zones (2021 boundaries), summarised for each SA4 zone (columns 2 to 10) and Greater Melbourne as a whole (column 11)}
\centering
\fontsize{8}{10}\selectfont
\begin{tabular}[t]{>{\raggedright\arraybackslash}p{1.75cm}|>{\raggedleft\arraybackslash}p{1cm}|>{\raggedleft\arraybackslash}p{1cm}|>{\raggedleft\arraybackslash}p{1cm}|>{\raggedleft\arraybackslash}p{1cm}|>{\raggedleft\arraybackslash}p{1cm}|>{\raggedleft\arraybackslash}p{1cm}|>{\raggedleft\arraybackslash}p{1cm}|>{\raggedleft\arraybackslash}p{1cm}|>{\raggedleft\arraybackslash}p{1cm}|>{\raggedleft\arraybackslash}p{1.25cm}}
\hline
Change & Inner & Inner East & Inner South & North East & North West & Outer East & South East & West & M'ton P'sula & Total\\
\hline
New service & 0.0\%     (0) & 0.0\%   (0) & 0.0\%   (0) & 1.6\%    (20) & 8.1\%  (79) & 0.1\%     (1) & 5.7\%   (113) & 4.4\%    (87) & 0.8\%   (6) & 2.7\%    (306)\\
\hline
Increased 30\% or more & 0.3\%     (5) & 0.1\%   (1) & 8.5\%  (83) & 8.3\%   (107) & 17.7\% (173) & 0.8\%    (10) & 14.8\%   (293) & 14.7\%   (290) & 21.4\% (154) & 9.7\%  (1,116)\\
\hline
Increased 10 to 30\% & 7.2\%   (104) & 0.8\%   (7) & 10.1\%  (99) & 7.4\%    (95) & 13.6\% (133) & 4.2\%    (54) & 8.7\%   (173) & 11.7\%   (231) & 6.8\%  (49) & 8.2\%    (945)\\
\hline
Increased 5 to 10\% & 11.6\%   (166) & 3.2\%  (28) & 12.3\% (120) & 7.0\%    (90) & 7.7\%  (75) & 5.4\%    (69) & 6.0\%   (120) & 11.8\%   (233) & 3.2\%  (23) & 8.0\%    (924)\\
\hline
Increased 3 to 5\% & 12.9\%   (185) & 6.7\%  (58) & 7.3\%  (71) & 11.4\%   (147) & 12.5\% (122) & 4.9\%    (63) & 5.2\%   (104) & 10.7\%   (210) & 4.4\%  (32) & 8.6\%    (992)\\
\hline
Increased 1 to 3\% & 19.6\%   (281) & 17.5\% (152) & 14.5\% (142) & 16.7\%   (214) & 11.0\% (107) & 7.9\%   (101) & 8.9\%   (176) & 13.8\%   (271) & 10.6\%  (76) & 13.2\%  (1,520)\\
\hline
Within 1\% & 19.9\%   (286) & 51.0\% (444) & 22.8\% (223) & 23.0\%   (295) & 14.2\% (138) & 51.9\%   (661) & 31.2\%   (620) & 17.6\%   (347) & 36.2\% (261) & 28.5\%  (3,275)\\
\hline
Reduced 1 to 3\% & 7.9\%   (114) & 10.8\%  (94) & 6.5\%  (63) & 6.9\%    (89) & 3.3\%  (32) & 7.2\%    (92) & 3.9\%    (77) & 2.2\%    (44) & 5.8\%  (42) & 5.6\%    (647)\\
\hline
Reduced 3 to 10\% & 14.8\%   (212) & 7.0\%  (61) & 10.2\% (100) & 8.2\%   (105) & 2.9\%  (28) & 8.0\%   (102) & 2.9\%    (58) & 4.0\%    (79) & 2.1\%  (15) & 6.6\%    (760)\\
\hline
Reduced by more than 10\% & 5.8\%    (83) & 2.8\%  (24) & 7.2\%  (70) & 4.0\%    (52) & 3.4\%  (33) & 6.0\%    (77) & 5.4\%   (108) & 3.2\%    (63) & 0.4\%   (3) & 4.5\%    (513)\\
\hline
Service withdrawn & 0.0\%     (0) & 0.0\%   (0) & 0.0\%   (0) & 0.3\%     (4) & 0.1\%   (1) & 0.2\%     (3) & 0.2\%     (3) & 0.2\%     (4) & 0.0\%   (0) & 0.1\%     (15)\\
\hline
Never served & 0.0\%     (0) & 0.1\%   (1) & 0.5\%   (5) & 5.2\%    (67) & 5.5\%  (54) & 3.2\%    (41) & 7.0\%   (139) & 5.5\%   (108) & 8.2\%  (59) & 4.1\%    (474)\\
\hline
Total & 100.0\% (1,436) & 100.0\% (870) & 100.0\% (976) & 100.0\% (1,285) & 100.0\% (975) & 100.0\% (1,274) & 100.0\% (1,984) & 100.0\% (1,967) & 100.0\% (720) & 100.0\% (11,487)\\
\hline
\end{tabular}
\end{table}

Figure \ref{fig:Greater_Melbourne_2016_2021_scatterplot_SA12021}
compares SI scores across Greater Melbourne (2021 SA1 boundaries) for
2016 and 2021. There is a significant and strong correlation between the
2016 and 2021 SI scores (\(r(11485) = 1.00\), \(p < .001\)). The average
SI score for SA1s across Greater Melbourne increased from 2,843.8 in
2016 to 2,901.4 in 2021 (+2.0\%). Table
\ref{tab:Greater_Melbourne_2016_2021_ratio_table} summarises changes in
SI score between 2016 and 2021 (column 1) by number of SA1 zones (2021
boundaries), summarised for each SA4 zone (columns 2 to 10) and Greater
Melbourne as a whole (column 11). 15 SA1s in Greater Melbourne (0.1\%)
that had some service in 2016 had no service at all in 2016, while 513
(4.5\%) had a fall in SI score of more than 10 percent. In contrast, 306
SA1s (2.7\%) with no service in 2016 received at least some service in
2021. 2,061 SA1s (17.9\%) had SI scores increase by 10 percent or more.

However, there was a statistically significant difference in the changes
in service levels across different parts of Greater Melbourne (using SA4
boundaries)(\(\chi^2(88) = 2829.67\), \(p < .001\)). SA1s with service
levels increases or new service were more likely in the north west
(70.7\%), west (67.2\%) and north east (52.4\%). Service levels were
more likely to have remained with 1\% of the 2016 levels in SA1s in the
Inner East (51.0\%), Outer East (51.9\%) and Mornington Peninsula
(36.2\%). SA1s more likely to have had service reductions were in the
Inner (28.5\%), Inner South (23.9\%) and Outer East (21.5\%).

\begin{figure}
\includegraphics[width=0.9\linewidth]{Leveraging_GTFS_to_assess_transit_supply_Transport_Geography_files/figure-latex/Greater_Melbourne_2016_2021_ratio_map-1} \caption{Greater Melbourne: changes in SI between 2016 and 2021, by SA1}\label{fig:Greater_Melbourne_2016_2021_ratio_map}
\end{figure}

Figure \ref{fig:Greater_Melbourne_2016_2021_ratio_map} maps the changes
in transit service levels. As well as the changes discussed above, the
map suggests other areas that have seen increases, including: around the
Dandenong, Cranbourne, Nar Nar Goon, Garfield and Bunyip areas (outer
south-east); some parts of the Mornington Peninsula; Kinglake (outer
north-east); and around Wallan (outer north). Decreased service levels,
in contrast are also evident: along the Stoney Point Line and Koo Wee
Rup (outer south-east); Heathcote Junction (north of Wallan); and around
Taylors Lakes and Syndenham.

\subsubsection{Social needs}\label{social-needs-1}

\begin{figure}
\includegraphics[width=0.9\linewidth]{Leveraging_GTFS_to_assess_transit_supply_Transport_Geography_files/figure-latex/Greater_Melbourne_2016_social_needs-1} \caption{Distribution of categories of composite social need index scores in 2016 (left) and 2021 (right), overlayed with: 2006 Greater Melbourne boundary (black); middle/outer and inner/middle suburb boundaries (grey); and suburban railway lines (dashed).}\label{fig:Greater_Melbourne_2016_social_needs}
\end{figure}

Figure \ref{fig:Greater_Melbourne_2016_social_needs} compares the
spatial patterns of social needs in 2016 and 2021. Overall, the spatial
patterns appear similar, with some areas in the north-west (Gisborne)
and south-east (Carrum Downs, Stoney Point) having Very High needs in
both. Some caution may be required in making direct comparisons of many
outer suburbs where residential development has led to the introduction
of new SA1s for the 2021 census. In many areas, including in the
south-west (Werribee), north-west (Romsey), north (Wallan, Beveridge,
Mickleham) and south-east (Clyde North and Beaconsfield South), it
appears there are still Very High transport needs but the spatial area
covered on the map is much smaller due to the redistricting of larger
SA1s into multiple SA1s. That said, it appears that:

\begin{itemize}
\tightlist
\item
  social needs fell in the southern parts of Bacchus Marsh and areas
  around Melton (outer west);
\item
  social needs rose in some outer northern (Lancefield), eastern
  (Gembrook East) and southern (end of the Mornington Penninsula) areas.
\end{itemize}

\subsubsection{Needs-gap analysis}\label{needs-gap-analysis-1}

\begin{figure}
\centering
\includegraphics{Leveraging_GTFS_to_assess_transit_supply_Transport_Geography_files/figure-latex/Greater_Melbourne_2016_needs_gap-1.pdf}
\caption{Greater Melbourne 2016, SI and Combined Needs Index scores,
with SI scores \textless{} 1 rounded up to equal 1.}
\end{figure}

Figure \ref{fig:Greater_Melbourne_2016_needs_gap} compares SI and
Combined Needs Index scores for SA1s in 2016. There is a significant,
but only weakly positive relationship.

\begin{table}

\caption{\label{tab:Greater_Melbourne_2016_needs_gap_zones}Greater Melbourne 2016, SA1s within each SI and Combined Needs Index grouping}
\centering
\fontsize{7}{9}\selectfont
\begin{tabular}[t]{l|r|r|r|r|r|r|r}
\hline
transit\_supply & Very Low & Low & Below average & Above average & High & Very High & Total\\
\hline
Zero Supply & 4.8\%    (91) & 3.5\%    (66) & 2.5\%    (47) & 2.4\%    (34) & 2.0\%    (28) & 3.2\%    (46) & 3.1\%   (312)\\
\hline
Very Low & 26.1\%   (497) & 23.2\%   (442) & 20.9\%   (397) & 20.4\%   (290) & 19.8\%   (281) & 22.5\%   (319) & 22.3\% (2,226)\\
\hline
Low & 24.1\%   (458) & 24.5\%   (467) & 24.4\%   (464) & 22.3\%   (317) & 21.7\%   (308) & 19.7\%   (279) & 23.0\% (2,293)\\
\hline
Below average & 24.9\%   (473) & 24.5\%   (467) & 24.1\%   (459) & 23.8\%   (338) & 23.2\%   (329) & 17.6\%   (249) & 23.2\% (2,315)\\
\hline
Above average & 7.4\%   (140) & 9.2\%   (175) & 10.2\%   (194) & 10.5\%   (149) & 10.6\%   (150) & 9.2\%   (131) & 9.4\%   (939)\\
\hline
High & 6.5\%   (123) & 7.5\%   (142) & 10.7\%   (203) & 10.2\%   (145) & 12.0\%   (170) & 10.9\%   (155) & 9.4\%   (938)\\
\hline
Very High & 6.4\%   (121) & 7.6\%   (144) & 7.3\%   (139) & 10.3\%   (146) & 10.7\%   (152) & 16.9\%   (239) & 9.4\%   (941)\\
\hline
Total & 100.0\% (1,903) & 100.0\% (1,903) & 100.0\% (1,903) & 100.0\% (1,419) & 100.0\% (1,418) & 100.0\% (1,418) & 100.0\% (9,964)\\
\hline
\end{tabular}
\end{table}

\begin{figure}
\centering
\includegraphics{Leveraging_GTFS_to_assess_transit_supply_Transport_Geography_files/figure-latex/Greater_Melbourne_2016_needs_gap_zones-1.pdf}
\caption{Greater Melbourne 2016, SA1s within each SI and Combined Needs
Index grouping}
\end{figure}

Figure \ref{fig:Greater_Melbourne_2016_needs_gap_zones} and Table
\ref{tab:Greater_Melbourne_2016_needs_gap_zones} compares the SI and
Combined Needs Index groupings for 2016. There is a statistically
significant relationship, although this appears to be weak. 365 SA1s
have zero or very low transit supply, but very high social needs. This
represents 3.7\% of the 9,964 SA1s within Greater Melbourne, and is a
higher proportion than that reported for 2006 (85 of 5,720 CCDs
(1.6\%)).

\begin{table}

\caption{\label{tab:Greater_Melbourne_2016_needs_gap_population}Greater Melbourne 2016, Population in each SI and Combined Needs Index grouping}
\centering
\fontsize{7}{9}\selectfont
\begin{tabular}[t]{>{\raggedright\arraybackslash}p{2cm}|>{\raggedleft\arraybackslash}p{1.16cm}|>{\raggedleft\arraybackslash}p{1.16cm}|>{\raggedleft\arraybackslash}p{1.16cm}|>{\raggedleft\arraybackslash}p{1.16cm}|>{\raggedleft\arraybackslash}p{1.16cm}|>{\raggedleft\arraybackslash}p{1.16cm}|>{\raggedleft\arraybackslash}p{1.5cm}}
\hline
transit\_supply & Very Low & Low & Below average & Above average & High & Very High & Total\\
\hline
Zero Supply & 4.3\%  (22,012) & 3.3\%  (22,544) & 2.4\%  (18,784) & 2.3\%  (15,402) & 1.9\%  (14,790) & 3.6\%    (38,050) & 2.9\%   (131,582)\\
\hline
Very Low & 24.8\% (126,298) & 23.1\% (156,359) & 20.8\% (165,350) & 20.5\% (138,710) & 20.1\% (153,169) & 25.1\%   (263,693) & 22.4\% (1,003,579)\\
\hline
Low & 24.8\% (126,411) & 24.9\% (168,228) & 24.8\% (197,542) & 22.8\% (154,275) & 22.1\% (168,541) & 19.1\%   (200,937) & 22.7\% (1,015,934)\\
\hline
Below average & 25.4\% (129,440) & 25.1\% (169,849) & 24.4\% (193,915) & 24.1\% (163,593) & 23.2\% (177,044) & 15.7\%   (164,681) & 22.3\%   (998,522)\\
\hline
Above average & 7.5\%  (38,003) & 9.1\%  (61,679) & 10.1\%  (80,591) & 10.3\%  (70,066) & 10.5\%  (80,172) & 8.1\%    (84,562) & 9.3\%   (415,073)\\
\hline
High & 6.6\%  (33,334) & 7.3\%  (49,615) & 10.4\%  (83,055) & 9.9\%  (67,061) & 11.7\%  (89,517) & 10.1\%   (105,960) & 9.6\%   (428,542)\\
\hline
Very High & 6.6\%  (33,361) & 7.2\%  (48,441) & 7.1\%  (56,303) & 10.1\%  (68,467) & 10.4\%  (79,329) & 18.3\%   (192,038) & 10.7\%   (477,939)\\
\hline
Total & 100.0\% (508,859) & 100.0\% (676,715) & 100.0\% (795,540) & 100.0\% (677,574) & 100.0\% (762,562) & 100.0\% (1,049,921) & 100.0\% (4,471,171)\\
\hline
\end{tabular}
\end{table}

\begin{figure}
\centering
\includegraphics{Leveraging_GTFS_to_assess_transit_supply_Transport_Geography_files/figure-latex/Greater_Melbourne_2016_needs_gap_population-1.pdf}
\caption{Greater Melbourne 2016, Populations within each SI and Combined
Needs Index grouping}
\end{figure}

Figure \ref{fig:Greater_Melbourne_2016_needs_gap_population} and Table
\ref{tab:Greater_Melbourne_2016_needs_gap_population} compares the
populations within each SI and Combined Needs Index grouping for 2016.
There is a statistically significant relationship, although this appears
to be weak. \ensuremath{3.01743\times 10^{5}} people live within SA1s
that have zero or very low transit supply, but very high social needs.
This represents 6.7\% of the 4,471,171 people within Greater Melbourne,
and is a lower proportion than that reported for 2006 (37,699 of 3.3
million people (8.2\%)).

\begin{figure}
\includegraphics[width=1\linewidth]{Leveraging_GTFS_to_assess_transit_supply_Transport_Geography_files/figure-latex/Greater_Melbourne_2016_needs_gap_map-1} \caption{Greater Melbourne 2016 SI groupings, overlayed with SA1s with very high transport need areas with zero or very low public transport supply (red).}\label{fig:Greater_Melbourne_2016_needs_gap_map}
\end{figure}

Figure \ref{fig:Greater_Melbourne_2016_needs_gap_map} shows SA1 zones in
Greater Melbourne with Very High transport needs, but Very Low or Zero
transit supply for 2016 (left) and 2021 (right) in red. There are no
SA1s within the inner suburbs with Very High transport needs, but Very
Low or Zero transit supply in either 2016 or 2021. In the middle suburbs
there appear to be some minor shifts, but the overall pattern in both
2016 and 2021 appears to be that there are isolated areas of Very High
transport needs, but Very Low or Zero transit supply in between train
lines. In the outer suburbs, however:

\begin{itemize}
\tightlist
\item
  areas around Werribee (south-west) continue to have Very High
  transport needs, but Very Low or Zero transit supply, and many of the
  changes between 2016 and 2021 appear to be related to new SA1 zones
  being added.
\item
  there appears to have been some improvement around Bacchus Marsh and
  Melton (west), but again, this may be an aterfact of some of the 2016
  SA1 zones having been split in 2021.\\
\item
  no improvements around Gisbourne (west-north-west)
\item
  some shifts around Lancefield and Romsey (north-west), Kilmore and
  west of Craigieburn (north-north-west), but again these may being in
  part due to boundary changes;
\item
  no improvement around Mernda, Diamond Creek and (west of) Hurstbridge
  (north-east) or around the outer eastern or south-eastern suburbs;
\item
  additions in the outter east and south including in parts of the
  Mornington Peninsula (south) and places close to Emerald and Gembrook.
\end{itemize}

\section{Discussion}\label{discussion}

\subsection{Limitations}\label{limitations}

\subsection{Directions for furture
research}\label{directions-for-furture-research}

\section{Conclusions}\label{conclusions}

\renewcommand\refname{References}
\bibliography{References.bib, packages.bib}


\end{document}
