\documentclass[preprint, 3p,
authoryear]{elsarticle} %review=doublespace preprint=single 5p=2 column
%%% Begin My package additions %%%%%%%%%%%%%%%%%%%

\usepackage[hyphens]{url}

  \journal{To be confirmed} % Sets Journal name

\usepackage{graphicx}
%%%%%%%%%%%%%%%% end my additions to header

\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
% TODO: Currently lineno needs to be loaded after amsmath because of conflict
% https://github.com/latex-lineno/lineno/issues/5
\usepackage{lineno} % add
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \usepackage{fontspec}
  \ifxetex
    \usepackage{xltxtra,xunicode}
  \fi
  \defaultfontfeatures{Mapping=tex-text,Scale=MatchLowercase}
  \newcommand{\euro}{€}
\fi
% use microtype if available
\IfFileExists{microtype.sty}{\usepackage{microtype}}{}
\usepackage[]{natbib}
\bibliographystyle{plainnat}

\usepackage{graphicx}
\ifxetex
  \usepackage[setpagesize=false, % page size defined by xetex
              unicode=false, % unicode breaks when used with xetex
              xetex]{hyperref}
\else
  \usepackage[unicode=true]{hyperref}
\fi
\hypersetup{breaklinks=true,
            bookmarks=true,
            pdfauthor={},
            pdftitle={Social needs for transport and gaps in transit service: new GTFS tools},
            colorlinks=false,
            urlcolor=blue,
            linkcolor=magenta,
            pdfborder={0 0 0}}

\setcounter{secnumdepth}{5}
% Pandoc toggle for numbering sections (defaults to be off)


% tightlist command for lists without linebreak
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}




\usepackage{subfig}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}



\begin{document}


\begin{frontmatter}

  \title{Social needs for transport and gaps in transit service: new
GTFS tools}
    \author[Public Transport Research Group (PTRG)]{James Reynolds%
  %
  \fnref{1}}
   \ead{james.reynolds@monash.edu} 
    \author[Public Transport Research Group (PTRG)]{Graham Currie%
  \corref{cor1}%
  \fnref{2}}
   \ead{graham.currie@monash.edu} 
    \author[Public Transport Research Group (PTRG)]{Yanda Qu%
  %
  \fnref{3}}
   \ead{yanda.qu@monash.edu} 
      \affiliation[Public Transport Research Group (PTRG)]{
    organization={Public Transport Research Group (PTRG), Institute of
Transport Studies, Department of Civil Engineering Engineering, Monash
University},addressline={Clayton
Campus},city={Melbourne},postcode={3800},state={Victoria},country={Australia},}
    \cortext[cor1]{Corresponding author}
    \fntext[1]{Research Fellow}
    \fntext[2]{Professor}
    \fntext[3]{PhD Student}
  
  \begin{abstract}
  Methods of identifying spatial areas where gaps between transit supply
  (accounting for both frequency and coverage) and social needs for
  transport needs are large have previously been presented in research
  literature (Currie 2010). However, this approach does not appear to
  have been widely adopted in practice or received much further
  attention from researchers. This may be due to the challenges
  associated with assessing transit supply levels prior to the
  widespread availability of electronic schedule data, but GTFS datasets
  are now provided by many operators. This paper reports the development
  of an R package of tools for using GTFS datasets for needs-gap
  analysis. Results for Melbourne in 2016 and 2021 are also presented,
  and show similar patterns as in the 2006 results reported in Currie
  (2010), with lower supply levels in outer areas and away from the rail
  network. The number of residents living in areas with Very High needs
  but Very Low or Zero transit supply has increased by 140\% from
  139,004 (4.2\%) in 2006 to 333,887 people (6.8\%) in 2021, while
  Melbourne's overall population increased by only 46\% (3.4m to 4.9m).
  The paper also briefly revists a case study of an early-2010s
  development in the outer south-east suburbs, reported in Delbosc et al
  (2015), finding that there have been positive changes in service level
  at this local scale, but that needs-gaps and lack of services appear
  to remain a challenge. While Melbourne may be an outlier in terms of
  population growth and (low) density, these results might suggest that
  providing even a basic level of transit-based mobility to those in
  need may have only become more difficult. Directions for further
  research and limitations are also identified.
  \end{abstract}
    \begin{keyword}
    social needs \sep public transport \sep social transit \sep spatial
analysis \sep 
    GTFS
  \end{keyword}
  
 \end{frontmatter}

\section{Introduction}\label{introduction}

Transit is provided for social reasons in many locations, allowing those
who cannot otherwise drive themselves to have at least some independent
motorised mobility \citep{Currie:2016aa}. Age, disability,
socio-economic status, lack of a vehicle and many other reasons might
make someone reliant on transit for some or all of their travel, and
even infrequent transit might provide a vital link to activities,
communities and services beyond walking distance. As well, fewer younger
people are obtaining a driving license than was the case previously
\citep{delbosc2013causes}, so there may be an increasing need for basic
transit coverage in the future.

Vertical social-equity perspectives on transport policy-making relate to
supporting those who are disadvantaged \citep{Litman:2016aa} and might
suggest providing at least some transit (and probably more than just a
minimum) where there are higher social needs for transport. Along these
lines \citet{Currie2003Hobart}, \citet{Currie2004Gap};
\citet{Currie2007Identifying} and \citet{currie2010identifying}
developed an approach for identifying spatial gaps in transit supply
related to social needs for transport, applying it to a case study of
Melbourne in 2006. However, there does not appear to have been much
further use or development of this spatial analysis technique. It is
also unclear whether the spatial patterns identified for Melbourne in
2006 have changed in the intervening years or if these are
representative of patterns in other places. This may be in part because,
until recently, schedules were not available in a consistent electronic
format, meaning that assessing transit supply often required bespoke
sourcing, cleaning and analysis for each operator. Nowadays, however,
more than 10,000 transit agencies publicly release timetable data in the
General Transit Feed Specification (GTFS) format \citep{GTFS}. Such
standardisation allows Google Maps and other online platforms to provide
transit-related outputs for any place publishing a feed. However, tools
for using GTFS data to examine spatial patterns and gaps in transit
supply with respect to social needs for transport do not appear to be
readily available. This gap, and the lack of direct follow up to
\citet{Currie2003Hobart}, \citet{Currie2004Gap},
\citet{Currie2007Identifying} and \citet{currie2010identifying}, provide
motivation for the research reported in this paper.

The objectives of this research are: (1) to develop tools for
undertaking needs-gap analysis using GTFS datasets; and (2) to better
understand spatial patterns of gaps between social needs for transport
and transit supply, including whether those reported in
\citet{Currie2007Identifying} and \citet{currie2010identifying} are
representative of the current situation in Melbourne and elsewhere. This
paper reports the development of a new R package
(\emph{gtfssupplyindex}) with tools for undertaking social needs-gaps
analysis using GTFS datasets. Also presented in this paper are results
for Melbourne in 2016 and 2021, matching the most recent
censuses\footnote{The wider programme of research includes examination
  of spatial gaps in other cities, so as to better understand whether
  patterns in Melbourne are representative. However, this paper is
  limited to Melbourne only. Results for other cities will be reported
  elsewhere.}. The remainder of the paper is structured as follows: the
next section outlines the research context; Section 3 describes the
study methodology; results are presented in Section 4 and discussed in
Section 5; and limitations of this study and directions for future
research are discussed in Section 6, which concludes the paper.

\section{Research context}\label{research-context}

There are many metrics available for assessing transit supply. Examples
include: those in the \emph{Transit Cooperative Research Program (TCRP)
Report 88: a guidebook for developing performance-measurement systems}
\citep{Ryus:2003aa}; and those used across benchmarking databases and
programs such as by the
\citet{Florida-Transit-Information-System:2018aa}, \citet{UITP:2015aa}
and \citet{Imperial-College-London:2023aa}.
\citet{FieldingGordonJ1987Mpts} provides a framework for combining
indicators of service inputs, outputs and consumption to describe cost
efficiency, cost effectiveness and service effectiveness. More broadly,
\citet{Litman:2003ab} and \citet{Litman:2016aa} discuss the traffic,
mobility, accessibility, social equity, strategic planning and other
rational decision-making perspectives underlying many transport
indicators; \citet{Reynolds:2017ah} extends these into models of how
institutionalism, incrementalism and other public policy analysis
concepts might apply to transit prioritisation;
\citet{GuzmanLuisA.2017Aeit} developed a measure of accessibility in the
context of policy development and social equity; and
\citet{Creutzig2020streetspaceallocation} introduced street space
allocation metrics based around ten ethical principles.

Many such metrics, however, may be difficult to calculate, understand or
use, especially for those who are not planners, engineers or otherwise
technical specialists. Where pre-calculated transit metrics are
immediately available it may not be possible to independently generate
scores or to assess proposed system changes. Contrasting examples are
provided by:

\begin{itemize}
\item
  \emph{Transit Score}s \citep{WalkScore:2023tg}, which are readily
  available online and rate a location out of 100 (representing the sort
  of transit accessibility experienced in the center of New York), but
  which cannot be calculated independently; and
\item
  the \emph{Transit Capacity and Quality of Service Manual (TCQSM)}
  \citep{TCQSM:2013}, which provides metrics for many aspects of transit
  systems, which can be independently calculated (with sufficient data),
  yet which may not be well suited for non-technical audiences.
\end{itemize}

GTFS datasets have allowed the application of such metrics to many
transit systems. The \emph{Transit Score} website itself provides an
example, reporting results for addresses across the globe, while
\citet{Wong:2013aa} provides another in reporting the distribution of
various \emph{TCQSM} metrics across 50 USA transit operators. Code used
in the \citet{Wong:2013aa} analysis is available for those who might
wish to produce similar analysis for other locations or time periods.
The lack of a similar code base for calculating spatial gaps in transit
supply with respect to social needs for transport provides the
motivation for the research reported in this paper.

\subsection{The Suppy Index (SI), Social Needs Index, and
Needs-gap}\label{the-suppy-index-si-social-needs-index-and-needs-gap}

The approach outlined in \citet{currie2010identifying} involves
calculating two scores for the geographical areas of interest: a Transit
Supply Index (SI) score; and a Composite Social Needs Index score. These
are then used to identify areas with Very High needs, but Very Low or
Zero transit supply. The SI incorporates both the frequency of transit
services and coverage of an area of interest. A generalized form of the
SI equation, adapted from \citet{currie2010identifying}, is:

\[SI_{area, time} = \sum{\frac{Area_{Bn}}{Area_{area}}SL_{n, time}}\]

where:

\begin{itemize}
\item
  \(SI_{area, time}\) is the Supply Index for the area of interest and a
  given period of time;
\item
  \(Area_{Bn}\) is the buffer area for each stop (n) within the area of
  interest\footnote{In \citet{currie2010identifying} this was based on a
    radius of 400 metres for bus and tram stops, and 800 metres for
    railway stations. The same definition is used here.};
\item
  \(Area_{area}\) is the area of the area of interest; and
\item
  \(SL_{n,time}\) is the number of transit arrivals for each stop within
  the given time period.
\end{itemize}

\begin{figure}

{\centering \subfloat[Distribution of Transit Supply\label{fig:Currie_map_SI-1}]{\includegraphics[width=0.5\linewidth]{graphics/Currie2010SI} }\subfloat[Distibution of Social Need for Transport\label{fig:Currie_map_SI-2}]{\includegraphics[width=0.5\linewidth]{graphics/Currie2010Needs} }\newline\subfloat[Supply Index and Composite Needs Index scores\label{fig:Currie_map_SI-3}]{\includegraphics[width=0.5\linewidth]{graphics/Currie2010chart} }\subfloat[CCDs with Very High needs and Very Low or Zero supply\label{fig:Currie_map_SI-4}]{\includegraphics[width=0.5\linewidth]{graphics/Currie2010gap} }\newline

}

\caption{Melbourne 2006 Social Needs-Gap Results. Source: Currie (2010)}\label{fig:Currie_map_SI}
\end{figure}

\citet{currie2010identifying} reported SI scores for Census Collection
Districts (CCDs) across Melbourne in 2006. These were used to categorise
service levels into seven groups, as shown in Figure
\ref{fig:Currie_map_SI}(a). General patterns were identified, being:
more transit supply in the inner and middle suburbs, and along passenger
railway lines; and outer areas tending to have very low supply or no
transit at all.

\citet{currie2010identifying} assessed the social need for transport
across Melbourne using a composite index, based on: the Australian
Bureau of Statistics' (ABS') Index of Related Socio-Economic
Advantage/Disadvantage (IRSAD) and a transport needs index derived from
eight weighted indicators. The spatial distribution of this Composite
Social Needs Index, reproduced in Figure \ref{fig:Currie_map_SI}(b),
showed that areas of Above Average, High and Very High social needs were
located in: some outer suburbs, particularly in the east and south-east;
and in some middle suburbs in the south-east, north and west.

As the final step in the social needs-gap analysis process
\citet{currie2010identifying} compared the Composite Social Needs Index
and Supply Index scores (Figure \ref{fig:Currie_map_SI}(c)), and
identified areas with Very High transport needs, but Very Low or Zero
transit supply (Figure \ref{fig:Currie_map_SI}(d)). Overall, ``8.2\% of
Melbourne residents ha(d) `very high' needs but `zero', `low' or `very
low' public transport supply'' \citep{currie2010identifying}, most of
whom appeared to be living in the outer suburbs.

This approach does not appear to have been adopted widely in practice or
by researchers. Our suspicion is that, while the SI has a relatively
simple formula and requires only geographic and timetable data to
calculate, a lack of software tools to complete the analysis may be
partly why it has not been more widely used. The methods used to develop
such tools are discussed in the following.

\section{Methodology}\label{methodology}

This study adopts a case research approach, which can be particularly
useful when research questions are about `how' or `why', but researchers
lack control of events (preventing experiments)\citep{Yin2009aa}. Here
the research questions relate to: (1) how to use GTFS data to assess
gaps between social needs and transit supply, and (2) how and why
spatial patterns might have changed since those reported for 2006 in
\citet{currie2010identifying}. There is no ability here to control
events, so a case research approach appears well suited to this study.

When using a case research approach there is a need to address the
``duality criterion'', being that the study should be seeking
generalisable findings while at the same time being grounded in the
context the (small number of) cases
\citep{Denscombe2007aa, Ketokivi2014aa}. Here the approach taken has
been to develop a package of tools for calculating the SI from GTFS data
using the R programming language \citep{R-base}, so that the duality
criterion is addressed by developing generic software functions that
might be applied to other GTFS feeds, beyond the Melbourne case reported
in this paper.

The recommendations of \citet{wickham2023r} informed the package setup
and development approach. Various existing packages and code examples
were relied upon including: \emph{sf} \citep{R-sf} for geospatial
analysis; the \emph{tidyverse} \citep{tidyverse2019}; \emph{gtfstools}
\citep{R-gtfstools}; and \emph{tidytransit} \citep{R-tidytransit}.

\subsection{Code developement}\label{code-developement}

Code was developed and tested on the Mornington Peninsula Tourist
Railway GTFS feed. This was selected primarily for convenience, given
its location in south-east Melbourne and the authors' familiarity with
the surrounding geography, and that the feed covers only a small number
of trips across just three stations (thereby facilitating hand
verification of outputs). Australian Bureau of Statistics (ABS) data was
used to define areas of interest, sourced via the \emph{absmapsdata}
package \citep{R-absmapsdata}.

\subsection{Melbourne Case Study}\label{melbourne-case-study}

\citet{Yin2009aa} notes selection of a case to allow longitudinal study,
and this is the primary reason for selecting Melbourne here. SI scores
were calculated using Census Collection Districts (CCDs), as in
\citet{currie2010identifying}, but for the weeks starting the days of
the 2016 and 2021 censuses. The Victorian GTFS feed was used, with
historical feeds sourced from \citet{transitfeeds_victoria:2023aa}.

Unfortunately, it is not possible to obtain 2016 or 2021 social
disadvantage data for CCDs, as the ABS no longer releases data using
this geographic scheme. Instead, population and other statistics are now
released for Statistical Areas (SAs), under a hierarchical structure
ranging from SA1s (averaging around 400 people) to SA4s (parts of a city
or region)\citep{ABSmaps}. As such, SI scores have also been calculated
for SA1s, to facilitate use of ABS data to identify needs-gaps.

This study adopts a similar approach to measuring social disadvantage as
used in \citet{currie2010identifying}, using: the ABS' IRSAD and a
transport needs index calculated from various other
statistics\footnote{The same need indicators and weightings used in
  \citet{currie2010identifying} were adopted, although \$799 or lower
  per week was used as the threshold for low income households rather
  than \$499 to account for inflation (as per the Reserve Bank of
  Australia's online inflation calculator).}. A composite needs
indicator was derived based on the IRSAD and the transport needs index,
again as per the \citet{currie2010identifying} approach. However,
changes to ABS reporting means that the composite needs indicator used
by \citet{currie2010identifying} cannot be exactly
replicated\footnote{The approach used here includes only two components
  in the composite needs index, in contrast to the four of
  \citet{currie2010identifying}. These were two ``relative need''
  components (obtained by weighting the IRSAD and the transport needs
  indexes by the population within the various needs groups for each
  area of interest). The other two components measured ``total need''
  (obtained by weighting the same two indexes by the total population in
  each area of interest).\\
  Current ABS reporting, however, does not allow the number of people
  within one or more of the various needs groups to be identified at the
  SA1 level. Hence, the ``relative need'' components could not be
  included here, and the composite index used in this analysis includes
  only the IRSAD index and the transport need index weighted by the
  total population of each SA1. These were then standardised and grouped
  into two sets of even groups (Very Low, Low and Below average; and
  Above average, High and Very High.) as per the six groups used by
  \citet{currie2010identifying}.}.

\section{Results}\label{results}

\subsection{The gtfssupplyindex
package}\label{the-gtfssupplyindex-package}

Code developed to calculate SI scores is available as an R package on
github (see \citet{gtfssupplyindex_github}). Included in the package is
a vignette (included as an Appendix to this paper) that outlines the
developed functions and provides step-by-step calculations for the
Mornington Peninsula Railway as a worked example, both using the package
tools and calculating by hand.

\subsection{Melbourne}\label{melbourne}

\subsubsection{Transport Supply
Categories}\label{transport-supply-categories}

\begin{table}

\caption{\label{tab:Greater_Melbourne_CCDs_SA1_table}Distribution of 2006, 2016 and 2021 Transport Supply to Melbourne CCDs (2006 boundaries), 2016 Transport Supply to Greater Melbourne (2016 SA1s) and 2021 Transport Supply to Greater Melbourne (2021 SA1s). Sources: 2006 values, Currie (2010); 2016 and 2021 values, authors' analysis}
\centering
\begin{tabular}[t]{l|r|r|r|r|r}
\hline
\multicolumn{1}{c|}{Transport} & \multicolumn{3}{c|}{CCDs} & \multicolumn{1}{c|}{2016 SA1s} & \multicolumn{1}{c}{2021 SA1s} \\
\cline{1-1} \cline{2-4} \cline{5-5} \cline{6-6}
Supply & 2006 & 2016 & 2021 & 2016 & 2021\\
\hline
Zero Supply & 3.2\%   (189) & 1.4\%    (86) & 1.3\%    (81) & 3.2\%    (326) & 4.3\%    (489)\\
\hline
Very Low & 22.5\% (1,314) & 23.5\% (1,485) & 23.3\% (1,474) & 23.0\%  (2,362) & 23.4\%  (2,692)\\
\hline
Low & 22.4\% (1,310) & 23.5\% (1,484) & 23.3\% (1,473) & 23.0\%  (2,362) & 23.4\%  (2,691)\\
\hline
Below average & 22.2\% (1,294) & 23.5\% (1,484) & 23.3\% (1,473) & 23.0\%  (2,362) & 23.4\%  (2,691)\\
\hline
Above average & 10.4\%   (608) & 9.4\%   (596) & 9.6\%   (608) & 9.3\%    (959) & 8.5\%    (975)\\
\hline
High & 9.2\%   (535) & 9.4\%   (595) & 9.6\%   (608) & 9.3\%    (959) & 8.5\%    (974)\\
\hline
Very High & 10.1\%   (589) & 9.4\%   (595) & 9.6\%   (608) & 9.3\%    (959) & 8.5\%    (975)\\
\hline
Total & 100.0\% (5,839) & 100.0\% (6,325) & 100.0\% (6,325) & 100.0\% (10,289) & 100.0\% (11,487)\\
\hline
\end{tabular}
\end{table}

Table \ref{tab:Greater_Melbourne_CCDs_SA1_table} summarises the
distribution of CCDs and SA1s across different Transport Supply
categories in 2006, 2016 and 2021. There is a statistically significant
difference in the shares of CCDs in each category between 2006, 2016 and
2021 (\(\chi^2(12, N = 18489) = 87.45\), \(p < .001\))\footnote{Differences
  are also statistically significant when comparing 2006 and 2016
  (\(\chi^2(6, N = 12164) = 56.87\), \(p < .001\)) or 2006 and 2021
  \(\chi^2(6, N = 12164) = 59.15\), \(p < .001\)), but not between 2016
  and 2021 (\(\chi^2(6, N = 12650) = 0.67\), \(p = .995\)).}. Only 81
CCDs (1.3\%) have Zero Supply in 2021, compared to the 189 (3.2\%)
reported by \citet{currie2010identifying} for 2006. These shares by
CCDs, however, are only for the 2006 extents of Melbourne. The ABS'
statistical boundary of ``Greater Melbourne'' now includes areas up to
around 30 kilometers further to the north. Figure
\ref{fig:Greater_Melbourne_population_2021_by_SA4} shows the spatial
distribution of Transport Supply by SA1 in 2021, including all of the
SA1s within the 2021 Greater Melbourne Greater Capital City Statistical
Area (GCCSA)\footnote{Additional maps showing Transport Supply by CCD
  and for 2016 are included in the Appendix.}. The 2006 boundary is
shown as an overlay, indicating that much of the new parts of Greater
Melbourne have Very Low or Zero supply levels. In general, however, the
spatial distribution of Transport Supply is similar to 2006 (Figure
\ref{fig:Currie_map_SI}(a)) with higher levels of Transport Supply in
more central areas and closer to suburban railway lines. The differences
between the share of areas of interest in each category in 2006 (by CCD)
and by SA1 in 2016 and 2021 are statistically significant
(\(\chi^2(12, N = 27615) = 58.86\), \(p < .001\))\footnote{Differences
  between 2006 and 2016, as a pair, are not statistically significant
  (\(\chi^2(6, N = 16128) = 8.83\), \(p = .183\)). Differences between
  2006 and 2021 are signficant (\(\chi^2(6, N = 17326) = 44.83\),
  \(p < .001\)) as are the differences between 2016 and 2021
  \(\chi^2(6, N = 21776) = 31.56\), \(p < .001\)).}.

\begin{table}

\caption{\label{tab:Greater_Melbourne_CCDs_SA1_population}Distribution of 2006, 2016 and 2021 Transport Supply to population in Melbourne. Sources: 2006 values, Currie (2010); 2016 and 2021 values, authors' analysis}
\centering
\begin{tabular}[t]{l|r|r|r}
\hline
Supply & 2006 & 2016 & 2021\\
\hline
Zero Supply & 2.5\%    (85,423) & 2.9\%   (131,619) & 3.8\%   (186,829)\\
\hline
Very Low & 23.6\%   (793,046) & 22.5\% (1,008,498) & 23.0\% (1,132,967)\\
\hline
Low & 25.7\%   (865,330) & 22.7\% (1,016,848) & 23.7\% (1,163,358)\\
\hline
Below average & 23.0\%   (774,521) & 22.3\% (1,000,290) & 23.6\% (1,159,783)\\
\hline
Above average & 9.6\%   (324,546) & 9.3\%   (418,614) & 8.7\%   (426,892)\\
\hline
High & 7.7\%   (260,411) & 9.6\%   (428,880) & 8.7\%   (425,779)\\
\hline
Very High & 7.8\%   (263,832) & 10.7\%   (480,469) & 8.6\%   (422,025)\\
\hline
Total & 100.0\% (3,367,109) & 100.0\% (4,485,218) & 100.0\% (4,917,633)\\
\hline
\end{tabular}
\end{table}

Table \ref{tab:Greater_Melbourne_CCDs_SA1_population} compares the share
of resident population in each transport supply category. Melbourne's
population increased by 46\% between 2006 (3,367,109) and 2021
(4,917,633), but the number of residents living in areas with Zero
Supply more than doubled from 85,423 (2.5\% of the total population) in
2006 to 186,829 (3.8\%) in 2021 (+119\%). The number of residents with
Zero or Very Low Transport Supply rose by 50\% from 878,469 (26.1\%) in
2006 to 1,319,796 (26.8\%) in 2021, while the number of those with
supply below the average (i.e.~Zero, Very Low, Low or Below Average)
rose by 45\% from 2,518,320 (74.8\%) in 2006 to 3,642,937 (74.1\%) in
2021. Between 2016 and 2021, Greater Melbourne's population increased by
10\%, but the number of residents in SA1s with Zero Supply rose by 42\%,
with Zero or Very Low Transport Supply rose by 16\%, and below the
average (Zero, Very Low, Low or Below Average) 15\%.

\begin{table}

\caption{\label{tab:Greater_Melbourne_population_2016_by_SA4}Greater Melbourne 2016: Share of population in each Transport Supply category for each SA4 region}
\centering
\fontsize{8}{10}\selectfont
\begin{tabular}[t]{>{\raggedright\arraybackslash}p{1.75cm}|>{\raggedleft\arraybackslash}p{1cm}|>{\raggedleft\arraybackslash}p{1cm}|>{\raggedleft\arraybackslash}p{1cm}|>{\raggedleft\arraybackslash}p{1cm}|>{\raggedleft\arraybackslash}p{1cm}|>{\raggedleft\arraybackslash}p{1cm}|>{\raggedleft\arraybackslash}p{1cm}|>{\raggedright\arraybackslash}p{1cm}|>{\raggedleft\arraybackslash}p{1cm}|>{\raggedleft\arraybackslash}p{1.25cm}}
\hline
Transport Supply & Inner & Inner East & Inner South & North East & North West & Outer East & South East & West & M'ton Pen. & Total\\
\hline
Zero Supply & 0.0\%       (0) & 0.0\%     (480) & 0.0\%   (1,604) & 0.4\%  (16,988) & 0.4\%  (17,655) & 0.3\%  (12,955) & 1.0\%  (44,757) & 0.3\%  (12,056) & 0.6\%  (25,124) & 2.9\%   (131,619)\\
\hline
Very Low & 0.1\%   (3,427) & 0.4\%  (18,454) & 0.6\%  (24,944) & 2.5\% (112,269) & 2.1\%  (94,853) & 4.3\% (190,890) & 4.8\% (215,217) & 4.2\% (186,665) & 3.6\% (161,779) & 22.5\% (1,008,498)\\
\hline
Low & 0.4\%  (18,018) & 0.9\%  (39,235) & 1.4\%  (60,833) & 2.7\% (119,608) & 2.4\% (107,693) & 3.0\% (135,247) & 5.0\% (224,097) & 5.4\% (242,438) & 1.6\%  (69,679) & 22.7\% (1,016,848)\\
\hline
Below average & 1.0\%  (42,950) & 2.3\% (105,168) & 2.9\% (128,014) & 2.9\% (132,008) & 2.2\%  (97,739) & 2.7\% (119,691) & 4.0\% (177,817) & 3.8\% (170,015) & 0.6\%  (26,888) & 22.3\% (1,000,290)\\
\hline
Above average & 1.0\%  (44,547) & 1.8\%  (80,002) & 1.8\%  (81,038) & 1.0\%  (46,965) & 0.6\%  (28,905) & 0.6\%  (25,188) & 1.2\%  (53,228) & 1.2\%  (54,895) & 0.1\%   (3,846) & 9.3\%   (418,614)\\
\hline
High & 2.9\% (129,533) & 1.7\%  (74,966) & 1.7\%  (74,617) & 1.0\%  (46,291) & 0.3\%  (14,464) & 0.3\%  (15,371) & 0.7\%  (33,365) & 0.9\%  (38,499) & 0.0\%   (1,774) & 9.6\%   (428,880)\\
\hline
Very High & 7.9\% (353,232) & 0.9\%  (41,416) & 0.7\%  (32,561) & 0.5\%  (21,197) & 0.0\%   (2,033) & 0.0\%     (314) & 0.2\%   (6,893) & 0.5\%  (22,823) & 0.0\%       (0) & 10.7\%   (480,469)\\
\hline
Total & 13.2\% (591,707) & 8.0\% (359,721) & 9.0\% (403,611) & 11.0\% (495,326) & 8.1\% (363,342) & 11.1\% (499,656) & 16.8\% (755,374) & 16.2\% (727,391) & 6.4\% (289,090) & 100.0\% (4,485,218)\\
\hline
\end{tabular}
\end{table}

\begin{table}

\caption{\label{tab:Greater_Melbourne_population_2021_by_SA4}Greater Melbourne 2021: Share of population in each Transport Supply category for each SA4 region}
\centering
\fontsize{8}{10}\selectfont
\begin{tabular}[t]{>{\raggedright\arraybackslash}p{1.75cm}|>{\raggedleft\arraybackslash}p{1cm}|>{\raggedleft\arraybackslash}p{1cm}|>{\raggedleft\arraybackslash}p{1cm}|>{\raggedleft\arraybackslash}p{1cm}|>{\raggedleft\arraybackslash}p{1cm}|>{\raggedleft\arraybackslash}p{1cm}|>{\raggedleft\arraybackslash}p{1cm}|>{\raggedright\arraybackslash}p{1cm}|>{\raggedleft\arraybackslash}p{1cm}|>{\raggedleft\arraybackslash}p{1.25cm}}
\hline
Transport Supply & Inner & Inner East & Inner South & North East & North West & Outer East & South East & West & M'ton Pen. & Total\\
\hline
Zero Supply & 0.0\%       (0) & 0.0\%     (478) & 0.0\%   (1,655) & 0.5\%  (26,563) & 0.5\%  (22,186) & 0.3\%  (14,125) & 1.1\%  (53,966) & 0.9\%  (43,898) & 0.5\%  (23,958) & 3.8\%   (186,829)\\
\hline
Very Low & 0.1\%   (4,169) & 0.4\%  (20,688) & 0.5\%  (22,483) & 2.7\% (130,715) & 2.3\% (110,814) & 4.1\% (200,810) & 5.1\% (250,684) & 4.5\% (221,337) & 3.5\% (171,267) & 23.0\% (1,132,967)\\
\hline
Low & 0.4\%  (20,329) & 0.9\%  (45,160) & 1.3\%  (63,802) & 2.7\% (132,001) & 2.5\% (123,314) & 3.2\% (155,603) & 5.4\% (265,995) & 5.9\% (289,518) & 1.4\%  (67,636) & 23.7\% (1,163,358)\\
\hline
Below average & 1.1\%  (54,918) & 2.7\% (133,305) & 3.0\% (148,585) & 3.1\% (151,240) & 2.6\% (129,918) & 2.3\% (114,658) & 4.2\% (204,093) & 3.8\% (184,466) & 0.8\%  (38,600) & 23.6\% (1,159,783)\\
\hline
Above average & 1.1\%  (56,422) & 1.4\%  (69,199) & 1.9\%  (92,875) & 0.9\%  (44,470) & 0.6\%  (27,140) & 0.5\%  (22,262) & 1.1\%  (53,328) & 1.1\%  (55,438) & 0.1\%   (5,758) & 8.7\%   (426,892)\\
\hline
High & 3.1\% (151,439) & 1.5\%  (73,687) & 1.4\%  (69,281) & 0.9\%  (43,985) & 0.2\%   (9,710) & 0.2\%  (10,905) & 0.5\%  (24,707) & 0.8\%  (41,100) & 0.0\%     (965) & 8.7\%   (425,779)\\
\hline
Very High & 6.7\% (329,654) & 0.6\%  (30,949) & 0.5\%  (23,906) & 0.2\%  (11,752) & 0.0\%   (1,285) & 0.0\%       (0) & 0.1\%   (7,308) & 0.3\%  (17,171) & 0.0\%       (0) & 8.6\%   (422,025)\\
\hline
Total & 12.5\% (616,931) & 7.6\% (373,466) & 8.6\% (422,587) & 11.0\% (540,726) & 8.6\% (424,367) & 10.5\% (518,363) & 17.5\% (860,081) & 17.3\% (852,928) & 6.3\% (308,184) & 100.0\% (4,917,633)\\
\hline
\end{tabular}
\end{table}

\begin{figure}
\includegraphics[width=1\linewidth]{ReynoldsCurrieQu2024_files/figure-latex/Greater_Melbourne_population_2021_by_SA4-1} \caption{Greater Melbourne 2021: Transport Supply by SA1,  overlayed with suburban rail network (black), SA4 boundaries (blue) and 2006 Melbourne extents (black)}\label{fig:Greater_Melbourne_population_2021_by_SA4}
\end{figure}

The SA4 boundaries divide Greater Melbourne into nine parts: three
`inner' zones; five `non-inner' zones; and the Mornington Peninsula,
which extends around the south-eastern part of Port Phillip Bay.
Variations in the share of SA1s in each Transport Supply category across
SA4 zones are statistically significant in both 2016
(\(\chi^2(48, N = 10289) = 6195.85\), \(p < .001\)) and 2021
(\(\chi^2(48, N = 11487) = 7250.39\), \(p < .001\)). Tables
\ref{tab:Greater_Melbourne_population_2016_by_SA4} and
\ref{tab:Greater_Melbourne_population_2021_by_SA4} show the population
in each supply category by SA4 for 2016 and 2021\footnote{Tables showing
  Transport Supply by number of SA1s for each SA4 are included in the
  Appendix.}. In general, larger shares of residents have lower than the
average supply in `non-Inner' parts of Greater Melbourne. In 2016,
2,714,128 residents (60.5\% of the total population of Greater
Melbourne) were both living outside of the inner three SA4s and in SA1s
with lower than average supply. By 2021 this had increased to 3,127,365
residents (63.6\%).

\subsubsection{Supply Index scores}\label{supply-index-scores}

\citet{currie2010identifying} reported an average SI score for CCDs in
2006 of 2,886.9 across Melbourne, with averages of 10,922.7, 2,694.9 and
764.3 for the inner, middle and outer suburbs, respectively. In
comparison, the average SI value found here for 2021 (using CCDs and
within the 2006 boundary) is 3,390, (+17\%), while it is 12,275.7
(+12\%), 3,409.1 (+27\%) and 998.96 (+31\%) for the inner, middle and
outer suburbs respectively\footnote{The same grouping of Local
  Government Areas (LGAs) to inner, middle and outer suburb groups as
  used in \citet{currie2010identifying} was used for this analysis,
  although here the City of Stonnington was allocated entirely to the
  middle grouping, whereas \citet{currie2010identifying} allocated part
  of this LGA to the inner group.}. Some caution is required, however,
as average scores found here might not be exactly comparable to those in
\citet{currie2010identifying} due to geographic
inconsistencies\footnote{The \citet{currie2010identifying} results show
  5,839 total CCDs within Melbourne, whereas the shape files obtained
  for this analysis include 6,325 CCDs within the 2006 Melbourne
  boundary.}, but in general the results appear to be consistent with
there having been increases in SI scores across all parts of Melbourne
since 2006. The general pattern of higher average SI scores in inner,
then middle, suburbs than in outer suburbs appears to remain unchanged.

\begin{table}

\caption{\label{tab:Greater_Melbourne_2016_2021_ratio_map_working}Greater Melbourne: Share of 2021 population living in SA1s by change in transit service (2016 vs 2021) by SA4 region}
\centering
\fontsize{8}{10}\selectfont
\begin{tabular}[t]{>{\raggedright\arraybackslash}p{1.75cm}|>{\raggedleft\arraybackslash}p{1cm}|>{\raggedleft\arraybackslash}p{1cm}|>{\raggedleft\arraybackslash}p{1cm}|>{\raggedleft\arraybackslash}p{1cm}|>{\raggedleft\arraybackslash}p{1cm}|>{\raggedleft\arraybackslash}p{1cm}|>{\raggedleft\arraybackslash}p{1cm}|>{\raggedright\arraybackslash}p{1cm}|>{\raggedleft\arraybackslash}p{1cm}|>{\raggedleft\arraybackslash}p{1.25cm}}
\hline
Change & Inner & Inner East & Inner South & North East & North West & Outer East & South East & West & M'ton Pen. & Total\\
\hline
New service & 0.0\%       (0) & 0.0\%       (0) & 0.0\%       (0) & 0.2\%   (9,911) & 0.7\%  (36,817) & 0.0\%     (238) & 1.1\%  (53,254) & 0.8\%  (40,483) & 0.1\%   (3,038) & 2.9\%   (143,741)\\
\hline
Increased 30\% or more & 0.0\%   (1,843) & 0.0\%     (279) & 0.8\%  (37,932) & 0.9\%  (46,448) & 1.7\%  (83,007) & 0.1\%   (4,209) & 2.6\% (127,248) & 2.7\% (131,194) & 1.3\%  (65,724) & 10.1\%   (497,884)\\
\hline
Increased 10 to 30\% & 0.9\%  (45,197) & 0.1\%   (3,190) & 0.8\%  (41,577) & 0.8\%  (40,989) & 1.1\%  (56,013) & 0.5\%  (22,609) & 1.6\%  (77,391) & 2.1\% (101,767) & 0.4\%  (21,060) & 8.3\%   (409,793)\\
\hline
Increased 5 to 10\% & 1.5\%  (72,360) & 0.3\%  (13,018) & 1.1\%  (52,033) & 0.8\%  (37,258) & 0.6\%  (31,400) & 0.5\%  (26,666) & 1.1\%  (53,370) & 2.1\% (101,769) & 0.2\%  (10,149) & 8.1\%   (398,023)\\
\hline
Increased 3 to 5\% & 1.6\%  (79,047) & 0.5\%  (25,074) & 0.6\%  (30,595) & 1.2\%  (60,661) & 1.1\%  (55,445) & 0.5\%  (23,819) & 0.9\%  (45,773) & 1.8\%  (88,601) & 0.3\%  (14,666) & 8.6\%   (423,681)\\
\hline
Increased 1 to 3\% & 2.3\% (115,203) & 1.4\%  (67,357) & 1.2\%  (60,889) & 1.9\%  (92,896) & 0.9\%  (42,761) & 0.8\%  (39,263) & 1.5\%  (75,676) & 2.4\% (117,967) & 0.7\%  (32,811) & 13.1\%   (644,823)\\
\hline
Within 1\% & 2.6\% (128,666) & 3.8\% (187,974) & 2.0\%  (97,037) & 2.5\% (124,942) & 1.2\%  (57,899) & 5.6\% (274,423) & 5.4\% (266,787) & 3.0\% (146,702) & 2.2\% (109,151) & 28.3\% (1,393,581)\\
\hline
Reduced 1 to 3\% & 1.0\%  (49,729) & 0.8\%  (39,675) & 0.6\%  (27,179) & 0.7\%  (34,180) & 0.3\%  (13,986) & 0.8\%  (38,826) & 0.7\%  (34,125) & 0.4\%  (19,517) & 0.4\%  (18,446) & 5.6\%   (275,663)\\
\hline
Reduced 3 to 10\% & 1.8\%  (89,662) & 0.5\%  (25,930) & 0.9\%  (42,701) & 0.9\%  (44,261) & 0.2\%  (11,175) & 0.9\%  (43,143) & 0.5\%  (24,903) & 0.7\%  (33,329) & 0.2\%   (7,953) & 6.6\%   (323,057)\\
\hline
Reduced 10\% or more & 0.7\%  (35,224) & 0.2\%  (10,491) & 0.6\%  (30,989) & 0.5\%  (22,617) & 0.3\%  (13,678) & 0.6\%  (31,042) & 1.0\%  (47,588) & 0.6\%  (27,701) & 0.0\%   (1,228) & 4.5\%   (220,558)\\
\hline
Service withdrawn (magenta) & 0.0\%       (0) & 0.0\%       (0) & 0.0\%       (0) & 0.0\%   (1,777) & 0.0\%     (424) & 0.0\%   (1,270) & 0.0\%   (1,360) & 0.0\%   (1,015) & 0.0\%       (0) & 0.1\%     (5,846)\\
\hline
Never served (black) & 0.0\%       (0) & 0.0\%     (478) & 0.0\%   (1,655) & 0.5\%  (24,786) & 0.4\%  (21,762) & 0.3\%  (12,855) & 1.1\%  (52,606) & 0.9\%  (42,883) & 0.5\%  (23,958) & 3.7\%   (180,983)\\
\hline
Total & 12.5\% (616,931) & 7.6\% (373,466) & 8.6\% (422,587) & 11.0\% (540,726) & 8.6\% (424,367) & 10.5\% (518,363) & 17.5\% (860,081) & 17.3\% (852,928) & 6.3\% (308,184) & 100.0\% (4,917,633)\\
\hline
\end{tabular}
\end{table}

\begin{figure}
\centering
\includegraphics{ReynoldsCurrieQu2024_files/figure-latex/Greater_Melbourne_2016_2021_ratio_map_plot-1.pdf}
\caption{Greater Melbourne: changes in SI between 2016 and 2021, by 2021
SA1, overlayed with 2006 Greater Melbourne boundary (black); 2021 SA4
boundaries (blue); and suburban railway lines (black)}
\end{figure}

Average SI scores for SA1s across all of Greater Melbourne, including
parts of the GCCSA that are beyond the 2006 boundary, increased from
2,843.8 in 2016 to 2,901.4 in 2021 (+2.0\%). There is a statistically
significant correlation between the 2016 and 2021 SI scores
(\(r(11485) = 1.00\), \(p < .001\), \(r_s =.98\), \(p < .001\)).

Figure 3 shows changes in SI scores between 2016 and 2021, categorised
into those SA1s where service levels have reduced by more than 1\% (3
groups), stayed within 1\% (1 group), increased (5 groups), or
introduced (1 group), were withdrawn (1 group) or were not provided in
either 2016 or 2021 (1 group). There is a statistically significant
difference in the proportion of SA1s in each service level change
category across SA4 areas (\(\chi^2(80) = 2818.27\),
\(p < .001\))\footnote{Service withdrawn category removed due to low
  numbers. See Appendix for table by SA1s.}. Table
\ref{tab:Greater_Melbourne_2016_2021_ratio_map_working} shows changes in
SI score between 2016 and 2021 (column 1) by the 2021 population,
summarised for each SA4 zone (columns 2 to 10) and for Greater Melbourne
as a whole (column 11). In 2021, slightly more than half of the
population across Greater Melbourne were living in SA1s where the SI
scores were at least one percent higher than they had been in 2016
(51.2\%, 2,517,945 people). The share of population for whom the SI
increased by at least one percent was highest in the North-West (72.0\%,
305,443 people) and West (68.2\%, 581,781 people) SA4s, and lowest in
the Inner East (29.2\%, 108,918 people) and Outer East (22.5\%, 116,804
people) SA4s.

The share of the population living in areas where the SI had dropped by
more than one percent was largest in the Inner (28.3\%, 174,615 people),
Inner South (23.9\%, 100,869 people) and Outer East (22.0\%, 114,281
people) SA4s.

Those living in SA1s that did not have transit service in 2021 and had
not had service in 2016 either numbered 180,983 people (3.7\%) in 2021
across all of Greater Melbourne. The share of the population living in
SA1s in 2021 that had been without transit in either 2016 or 2021 was
highest amongst the Mornington Peninsula (7.8\%, 23,958 people) and
South East (6.1\%, 52,606, people) SA4s, whereas no one at all in the
Inner SA4 in 2021 was living in a SA1 without at least a Very Low
service level. Service had been withdrawn since 2016 for SA1s
accommodating 5,846 residents in 2021 across all of Greater Melbourne
(0.1\%). The share of the population living in 2021 in SA1 where transit
service had been withdrawn since 2016 was largest in the Mornington
Peninsula (7.8\%, 23,958) and South East (6.1\%, 52,606) SA4s.

\subsubsection{Social needs}\label{social-needs}

\begin{figure}
\centering
\includegraphics{ReynoldsCurrieQu2024_files/figure-latex/Greater_Melbourne_2021_social_needs-1.pdf}
\caption{Greater Melbourne 2021: Distribution of categories of composite
social need index scores, overlayed with: 2006 Greater Melbourne
boundary (black); SA4 boundaries (blue); and suburban railway lines
(black).}
\end{figure}

Figure 4 shows the distribution of categories of social need index
scores across Greater Melbourne for 2021\footnote{A map for 2016 is
  included in the Appendix.}. This is analogous to the 2006 map shown in
Figure \ref{fig:Currie_map_SI}(b)\footnote{although, as discussed in the
  methodology section above, it was not possible to exactly replicate
  the \citet{currie2010identifying} social needs scoring approach due to
  changes in how census results are reported.}. In general, the
different levels of social need appears less consistently grouped in
2021 than in 2006, although this may be an artifact of the shift from
CCDs to (the smaller) SA1s.

\subsubsection{Needs-gap}\label{needs-gap}

\begin{table}

\caption{\label{tab:Greater_Melbourne_2021_needs_gap_population}Greater Melbourne 2021, Population in each SI and Combined Needs Index grouping}
\centering
\fontsize{8}{10}\selectfont
\begin{tabular}[t]{>{\raggedright\arraybackslash}p{2.5cm}|>{\raggedleft\arraybackslash}p{1.25cm}|>{\raggedleft\arraybackslash}p{1.25cm}|>{\raggedleft\arraybackslash}p{1.25cm}|>{\raggedleft\arraybackslash}p{1.25cm}|>{\raggedleft\arraybackslash}p{1.25cm}|>{\raggedleft\arraybackslash}p{1.25cm}|>{\raggedleft\arraybackslash}p{1.5cm}}
\hline
\multicolumn{1}{c|}{ } & \multicolumn{6}{c|}{Combined Needs Index Category} & \multicolumn{1}{c}{ } \\
\cline{2-7}
Supply & Very High & High & Above Average & Below Average & Low & Very Low & Total\\
\hline
Zero Supply & 0.9\%    (41,915) & 0.6\%  (27,179) & 0.5\%  (22,705) & 0.7\%  (32,328) & 0.7\%  (32,645) & 0.6\%  (30,002) & 3.8\%   (186,774)\\
\hline
Very Low & 6.0\%   (291,972) & 4.1\% (199,467) & 3.4\% (165,968) & 3.7\% (182,624) & 3.2\% (158,222) & 2.6\% (129,608) & 23.0\% (1,127,861)\\
\hline
Low & 4.9\%   (239,199) & 4.2\% (205,465) & 3.9\% (193,243) & 4.3\% (210,576) & 3.7\% (183,333) & 2.7\% (130,779) & 23.7\% (1,162,595)\\
\hline
Below average & 4.7\%   (228,646) & 4.5\% (219,310) & 4.2\% (204,049) & 4.2\% (203,750) & 3.5\% (171,997) & 2.7\% (130,322) & 23.6\% (1,158,074)\\
\hline
Above average & 2.0\%   (100,326) & 1.6\%  (80,404) & 1.5\%  (73,669) & 1.6\%  (76,179) & 1.2\%  (56,902) & 0.8\%  (37,419) & 8.7\%   (424,899)\\
\hline
High & 2.2\%   (107,121) & 1.7\%  (83,970) & 1.4\%  (70,132) & 1.6\%  (77,358) & 1.1\%  (54,528) & 0.7\%  (32,274) & 8.7\%   (425,383)\\
\hline
Very High & 2.6\%   (129,759) & 1.6\%  (79,306) & 1.2\%  (59,356) & 1.1\%  (55,828) & 1.1\%  (54,061) & 0.8\%  (40,417) & 8.5\%   (418,727)\\
\hline
Total & 23.2\% (1,138,938) & 18.3\% (895,101) & 16.1\% (789,122) & 17.1\% (838,643) & 14.5\% (711,688) & 10.8\% (530,821) & 100.0\% (4,904,313)\\
\hline
\end{tabular}
\end{table}

\begin{table}

\caption{\label{tab:Greater_Melbourne_2016_needs_gap_population}Greater Melbourne 2016, Population in each SI and Combined Needs Index grouping}
\centering
\fontsize{8}{10}\selectfont
\begin{tabular}[t]{>{\raggedright\arraybackslash}p{2.5cm}|>{\raggedleft\arraybackslash}p{1.25cm}|>{\raggedleft\arraybackslash}p{1.25cm}|>{\raggedleft\arraybackslash}p{1.25cm}|>{\raggedleft\arraybackslash}p{1.25cm}|>{\raggedleft\arraybackslash}p{1.25cm}|>{\raggedleft\arraybackslash}p{1.25cm}|>{\raggedleft\arraybackslash}p{1.5cm}}
\hline
\multicolumn{1}{c|}{ } & \multicolumn{6}{c|}{Combined Needs Index Category} & \multicolumn{1}{c}{ } \\
\cline{2-7}
Supply & Very High & High & Above Average & Below Average & Low & Very Low & Total\\
\hline
Zero Supply & 0.9\%    (38,050) & 0.3\%  (14,790) & 0.3\%  (15,402) & 0.4\%  (18,784) & 0.5\%  (22,544) & 0.5\%  (22,012) & 2.9\%   (131,582)\\
\hline
Very Low & 5.9\%   (263,693) & 3.4\% (153,169) & 3.1\% (138,710) & 3.7\% (165,350) & 3.5\% (156,359) & 2.8\% (126,298) & 22.4\% (1,003,579)\\
\hline
Low & 4.5\%   (200,937) & 3.8\% (168,541) & 3.5\% (154,275) & 4.4\% (197,542) & 3.8\% (168,228) & 2.8\% (126,411) & 22.7\% (1,015,934)\\
\hline
Below average & 3.7\%   (164,681) & 4.0\% (177,044) & 3.7\% (163,593) & 4.3\% (193,915) & 3.8\% (169,849) & 2.9\% (129,440) & 22.3\%   (998,522)\\
\hline
Above average & 1.9\%    (84,562) & 1.8\%  (80,172) & 1.6\%  (70,066) & 1.8\%  (80,591) & 1.4\%  (61,679) & 0.8\%  (38,003) & 9.3\%   (415,073)\\
\hline
High & 2.4\%   (105,960) & 2.0\%  (89,517) & 1.5\%  (67,061) & 1.9\%  (83,055) & 1.1\%  (49,615) & 0.7\%  (33,334) & 9.6\%   (428,542)\\
\hline
Very High & 4.3\%   (192,038) & 1.8\%  (79,329) & 1.5\%  (68,467) & 1.3\%  (56,303) & 1.1\%  (48,441) & 0.7\%  (33,361) & 10.7\%   (477,939)\\
\hline
Total & 23.5\% (1,049,921) & 17.1\% (762,562) & 15.2\% (677,574) & 17.8\% (795,540) & 15.1\% (676,715) & 11.4\% (508,859) & 100.0\% (4,471,171)\\
\hline
\end{tabular}
\end{table}

\begin{figure}
\centering
\includegraphics{ReynoldsCurrieQu2024_files/figure-latex/Greater_Melbourne_2021_needs_gap_scatterplot_figure-1.pdf}
\caption{Greater Melbourne 2021, SI and Combined Needs Index scores,
with SI scores \textless{} 10 rounded up to equal 10 to improve
clarity.}
\end{figure}

Figure 5 shows social needs and SI scores for 2021\footnote{To improve
  the clarity of the figure, SI scores less than 10 have been adjusted
  to equal 10. As well, those SA1s with combinations of Zero or Very Low
  Transport Supply and (especially) high needs scores (more than 40); or
  Very High supply and Very Low needs scores (less than 4.5) have been
  labelled with their SA2 name, so as to given an indication of which
  suburbs of Melbourne are at each of the extremes. A similar plot for
  2016 is shown in the Appendix.}, and is analogous to the 2006 plot
shown in Figure 1(c). SA1s with particularly low needs scores and Very
High supply are labeled, and are mostly in inner parts of the
city\footnote{Including CBD, Richmond and Collingwood. Broadmeadows and
  Box Hill are notable exceptions, however, being located in the middle
  suburbs and having major railway stations.}, Those with particularly
high needs and Very Low supply are similarly labeled, and are all in the
outer suburbs. There is a significant, but only weakly positive
correlation between the SI and Combined Needs Index scores for both 2016
(\(r(11136) = .06\), \(p < .001\), \(r_s =.07\), \(p < .001\)) and 2021
(\(r(11136) = .06\), \(p < .001\), \(r_s =.07\), \(p < .001\)).

Differences in the share of SA1s in each Transport Supply category
across different Combined Needs Index categories are statistically
significant in 2016 (\(\chi^2(30, N = 9964) = 264.26\), \(p < .001\))
and 2021 (\(\chi^2(30, N = 11138) = 133.51\), \(p < .001\) )\footnote{See
  Appendix for tables by SA1}. Tables
\ref{tab:Greater_Melbourne_2016_needs_gap_population} and
\ref{tab:Greater_Melbourne_2021_needs_gap_population} compare the
populations within each Transport Supply and Combined Needs Index
grouping for 2016 and 2021. In 2016 301,743 people lived within SA1s
that had Zero or Very Low Transport Supply, but Very High social needs
(6.7\% of the total population). By 2021 this had increased to 333,887
people (+11\%, 6.7\% of the total population). compared to the 139,004
people reported in \citet{currie2010identifying} for 2006 (4.2\% of the
population).

\begin{figure}
\centering
\includegraphics{ReynoldsCurrieQu2024_files/figure-latex/Greater_Melbourne_2021_needs_gap_map_figure-1.pdf}
\caption{Greater Melbourne 2021: Transport Supply groupings for Very
High needs SA1s (only)}
\end{figure}

Figure 6 shows SA1 zones in Greater Melbourne with Very High transport
needs, but Very Low or Zero Transport Supply for 2021, and is analogous
to the 2006 distribution shown in Figure \ref{fig:Currie_map_SI}(d).
Comparison suggests that areas with larger gaps between social needs and
transport supply continue to be mostly in the outer areas of Melbourne.

\subsubsection{Service level changes for those with the largest
needs-gaps in
2016}\label{service-level-changes-for-those-with-the-largest-needs-gaps-in-2016}

\begin{table}

\caption{\label{tab:Greater_Melbourne_2016_needs_gap_SA4_service_change}Greater Melbourne: 2016 residents living in areas with Very High needs but Very Low or Zero supply, by SA4 and change in SI by 2021}
\centering
\fontsize{8}{10}\selectfont
\begin{tabular}[t]{>{\raggedright\arraybackslash}p{2.5cm}|>{\raggedleft\arraybackslash}p{1cm}|>{\raggedleft\arraybackslash}p{1cm}|>{\raggedleft\arraybackslash}p{1cm}|>{\raggedleft\arraybackslash}p{1cm}|>{\raggedleft\arraybackslash}p{1cm}|>{\raggedleft\arraybackslash}p{1cm}|>{\raggedleft\arraybackslash}p{1cm}|>{\raggedright\arraybackslash}p{1cm}|>{\raggedleft\arraybackslash}p{1.25cm}}
\hline
Change & Inner & Inner South & North East & North West & Outer East & South East & West & M'ton Pen. & Total\\
\hline
New or 30\%+ & 0.0\%     (0) & 0.5\% (1,512) & 3.6\% (10,928) & 7.2\% (21,707) & 0.0\%      (0) & 15.0\% (45,117) & 10.8\% (32,552) & 1.8\%  (5,342) & 38.8\% (117,158)\\
\hline
Increased 1 to 30\% & 0.2\%   (568) & 0.2\%   (648) & 3.4\% (10,172) & 3.0\%  (8,973) & 1.9\%  (5,843) & 6.5\% (19,533) & 7.6\% (22,823) & 2.1\%  (6,188) & 24.8\%  (74,748)\\
\hline
Within 1\% & 0.2\%   (546) & 0.4\% (1,271) & 1.9\%  (5,639) & 0.3\%    (953) & 4.8\% (14,489) & 5.3\% (15,974) & 4.1\% (12,378) & 4.1\% (12,421) & 21.1\%  (63,671)\\
\hline
Reduced, withdrawn, never & 0.0\%     (0) & 0.8\% (2,473) & 4.3\% (13,064) & 0.6\%  (1,878) & 1.2\%  (3,619) & 1.9\%  (5,835) & 3.9\% (11,773) & 2.5\%  (7,524) & 15.3\%  (46,166)\\
\hline
Total & 0.4\% (1,114) & 2.0\% (5,904) & 13.2\% (39,803) & 11.1\% (33,511) & 7.9\% (23,951) & 28.7\% (86,459) & 26.4\% (79,526) & 10.4\% (31,475) & 100.0\% (301,743)\\
\hline
\end{tabular}
\end{table}

\begin{figure}
\centering
\includegraphics{ReynoldsCurrieQu2024_files/figure-latex/Greater_Melbourne_2016_needs_gap_SA4_service_change-1.pdf}
\caption{Greater Melbourne: change in transit supply between 2016 and
2021 for SA1s with Very High needs but Very Low or Zero supply in 2016}
\end{figure}

Figure 7 shows the change in transit supply between 2016 and 2021 for
those SA1s that had Very High needs but Very Low or Zero supply in 2016,
while Table
\ref{tab:Greater_Melbourne_2016_needs_gap_SA4_service_change} shows it
by the 2016 population. This type of analysis was not included in
\citet{currie2010identifying}, but is possible here as there is
logitudinal service data. There is a statistically significant variation
across the non-Inner SA4s\footnote{The change in service level has been
  collapsed into four categories, and the Inner, Inner East and Inner
  South SA4s have been removed to meet assumptions of the chi-square
  test. A table by SA1 is included in the Appendix.}
(\(\chi^2(15) = 92.59\), \(p < .001\)). Service levels had increased by
2021 for most of those living in Very High needs but Very Low or Zero
supply SA1s in 2016 in the North West (92\%, 30,680 people), South East
(75\%, 64,650 people), West (70\%, 55,375 people) and North East (53\%,
21,100 people) SA4s. Services had been reduced or withdrawn, or were
never present for SA1s with Very High needs and Very Low or Zero supply
in 2016 that covered 33\% of people living in the North East (13,064
people), 24\% in the Mornington Peninsula (7,524 people), 15\% in the
West (11,773 people) and 15\% in the Outer East (3,619 people).

\section{Discussion}\label{discussion}

The maps, tables and other outputs presented in this paper demonstrate
some of the analysis possible using the new \emph{gtfssupplyindex}
package. Longitudinal comparison of transit service levels has been
shown in aggregate (Table
\ref{tab:Greater_Melbourne_CCDs_SA1_population}), by population across
sub-areas (in comparing Tables
\ref{tab:Greater_Melbourne_population_2016_by_SA4} and
\ref{tab:Greater_Melbourne_population_2021_by_SA4}) and mapped (Figure
3). Visual display of needs-gaps have also been shown through
scatterplots (Figure 5) and mapping (Figure 6\}. Such outputs,
especially if produced at the spatial level of a neighbourhood, council
ward or electoral division, might be useful for advocates and
professionals seeking to identify and demonstrate which spatial areas
might benefit most from increased transit, and where available funds
might best be directed. Figure 7 and Table 8 show how the needs-gap
analysis approach and longitudinal data can track changes for those
residents with the highest unmet needs. Results suggest that SA1s that
were home to 13,064 people in 2016 in the North East, 11,773 in the
West, 7,524 in the Mornington Peninsula and a further 13,805 in other
parts of Greater Melbourne had transit service reduced or withdrawn by
2021, or had no service in either year, despite having had amongst the
largest needs-gaps in 2016. Questions of why this is the case appear
likely to vary from location to location, but Figure 7 or similar maps
for other cities might provide a useful starting point for exploring how
to reduce gaps in transit with respect to social needs.

Along these lines, Figures \ref{fig:Bus_798}, \ref{fig:Selandra_rise}
and \ref{fig:Selandra_rise_2021} show the Selandra Rise estate,
returning to the (then new) outer suburban development that was examined
in a case study reported by \citet{delbosc2015impact}. The estate is
served by the 798 bus route, which was reported as having around 2,500
boardings per week and being used by at least one person in 35 percent
of households within the Selandra Rise Estate, despite it not
penetrating fully into the development at that time (Figure
\ref{fig:Bus_798}a), and only 20 percent of the estate's footprint being
within 400 metres of the route. Case study findings suggested that: the
route was ``performing an important `social transit' function''; that
``those who do use the bus use it very frequently (88 percent (of
riders) at least a few days a week)''; ``Most bus riders were young and
could not drive or had no car available, making them quite reliant on
the bus'', and that it ``frees up the time of other household members
who would have had to provide lifts'' \citep[10]{delbosc2015impact}.

\begin{figure}

{\centering \subfloat[Transit routes: 2014 (Source: Delbosc et al (2015) overlaid on PTV(2014))\label{fig:Bus_798-1}]{\includegraphics[width=0.5\linewidth]{graphics/Cranbourne2014} }\subfloat[Transit routes: 2021 (Source: PTV(2021))\label{fig:Bus_798-2}]{\includegraphics[width=0.5\linewidth]{graphics/Cranbourne2021} }

}

\caption{Cranbourne and Selandra Rise}\label{fig:Bus_798}
\end{figure}

\begin{figure}

\subfloat[Transport Supply by SA1: 2016\label{fig:Selandra_rise-1}]{\includegraphics{ReynoldsCurrieQu2024_files/figure-latex/Selandra_rise-1} }\subfloat[Transport Supply by population: 2016\label{fig:Selandra_rise-2}]{\includegraphics{ReynoldsCurrieQu2024_files/figure-latex/Selandra_rise-2} }\newline\subfloat[Transport Supply by SA1: 2021\label{fig:Selandra_rise-3}]{\includegraphics{ReynoldsCurrieQu2024_files/figure-latex/Selandra_rise-3} }\subfloat[Transport Supply by population: 2021\label{fig:Selandra_rise-4}]{\includegraphics{ReynoldsCurrieQu2024_files/figure-latex/Selandra_rise-4} }\newline\subfloat[Change in SI score between 2016 and 2021 by SA1\label{fig:Selandra_rise-5}]{\includegraphics{ReynoldsCurrieQu2024_files/figure-latex/Selandra_rise-5} }\subfloat[...by 2021 population (COPYEDIT note: adjust to align with above during production)\label{fig:Selandra_rise-6}]{\includegraphics{ReynoldsCurrieQu2024_files/figure-latex/Selandra_rise-6} }\newline\hfill{}

\caption{Cranbourne and the Selandra Rise Estate}\label{fig:Selandra_rise}
\end{figure}

\begin{figure}

\subfloat[Social Need by SA1: 2016\label{fig:Selandra_rise_2021-1}]{\includegraphics{ReynoldsCurrieQu2024_files/figure-latex/Selandra_rise_2021-1} }\subfloat[Social Need by population: 2016\label{fig:Selandra_rise_2021-2}]{\includegraphics{ReynoldsCurrieQu2024_files/figure-latex/Selandra_rise_2021-2} }\newline\subfloat[SA1s with Very High needs and Very Low or Zero supply in 2016, change in SI by 2021\label{fig:Selandra_rise_2021-3}]{\includegraphics{ReynoldsCurrieQu2024_files/figure-latex/Selandra_rise_2021-3} }\subfloat[...by 2016 population (COPYEDIT note: shift to align with others\label{fig:Selandra_rise_2021-4}]{\includegraphics{ReynoldsCurrieQu2024_files/figure-latex/Selandra_rise_2021-4} }\newline\subfloat[Social Need by SA1: 2021\label{fig:Selandra_rise_2021-5}]{\includegraphics{ReynoldsCurrieQu2024_files/figure-latex/Selandra_rise_2021-5} }\subfloat[Social Need by population: 2021\label{fig:Selandra_rise_2021-6}]{\includegraphics{ReynoldsCurrieQu2024_files/figure-latex/Selandra_rise_2021-6} }\newline\subfloat[SA1s with Very High needs in 2021, Supply by SA1\label{fig:Selandra_rise_2021-7}]{\includegraphics{ReynoldsCurrieQu2024_files/figure-latex/Selandra_rise_2021-7} }\subfloat[...by population\label{fig:Selandra_rise_2021-8}]{\includegraphics{ReynoldsCurrieQu2024_files/figure-latex/Selandra_rise_2021-8} }\newline\hfill{}

\caption{Cranbourne and the Selandra Rise Estate, overlayed with transit routes (purple)}\label{fig:Selandra_rise_2021}
\end{figure}

Examining Selandra Rise through the lens of the needs-gap approach shows
that it had Very Low supply in 2016 (Figure 9a), but that by 2021
service for some parts of the estate had increase to be in the Low or
Below Average categories (Figure 9c). Figures 9b and 9c show the
distribution of the population within those SA1s shown in Figures 9a an
9c, indicating that overall population rose from a little under 55,000
in 2016 to a little over 87,000 in 2021, but that more than half of
these people lived in SA1s with Very Low (almost 36,000, 41\%) or Zero
supply (15,200, 17\%). SI scores increased for SA1s in the Selandra
Estate, but areas to the north-west and south-west have seen falls of
10\% or more (Figure 9e). SA1s to the east of the Selandra Rise estate
did not have a transit service at all in 2021, although this appears to
have been resolved by 2024 through the extension of the 898 (Figure 8d).

The Selandra Rise estate had Very High needs in 2016, but some parts of
the estate had lower needs by 2021 (Figure \ref{fig:Selandra_rise_2021}a
\& e). For most of those who had Very High needs, but Very Low or Zero
Supply in 2016 (c \& d), service levels rose by at least 1\% or new
services had been introduced by 2021. However, some 817 people living in
a Very High need, Very Low supply SA1 to the north of the Selandra in
2016 are shown in the ``Reduced, withdrawn or never served'' category in
Figure \ref{fig:Selandra_rise_2021}d.~Closer inspection indicates that
these people were in a SA1 (2016 boundaries) where the SI dropped from
198 to 140 (almost 30\%). Figure 10g shows a SA1 with Zero supply and
718 in the same geographical area in the north. Various other nearby
SA1s with Very High Needs also have Zero supply, making up around 20\%
(4,878) of the Very High needs population in the estate and surrounding
areas. A further 12,729 people (52\% of the Very High needs population)
had Very Low supply, suggesting that much of Selandra Rise and
surrounding areas remained among those parts of Greater Melbourne twith
the most need, but least supply.

\section{Conclusions}\label{conclusions}

This research was motivated by a lack of software tools to analyse gaps
between social needs for transport and the amount of transit provided,
and a need to better understand how spatial patterns might have changed
since the original development of this analysis approach in the early
2000s. The needs-gaps approach was suggested to be ``substantially more
useful than the presentation of anecdotal evidence, which is the most
common means of identifying transport needs in local transport studies
throughout the world'' \citep{currie2010identifying}, yet this technique
does not appear to have been widely adopted in practice or received much
further attention from researchers. The results reported in this paper,
therefore, are important because they may help bridge gaps between
research (where the needs-gap approach and SI formulation was developed)
and the real world of transport planning, advocacy, professional
practice and politics (where decisions are made about where transit
services are needed or need improving).

As discussed in Section 2, there are many transit metrics available, but
some cannot be calculated independently. The SI combines accessibility
(coverage) and service frequency into a single and relatively simply
measure, which can now be calculated using the new
\emph{gtfssupplyindex} package with only a GTFS feed, geographic data
and some computer time. While the tool is not yet at a point and click
level of usability (i.e.~like \emph{TransitScore}), it is open source
and publicly available, and so may make assessing transit service levels
and network change proposals with respect to social needs for transport
more widely achievable.

This paper has also demonstrated how this package might be applied
through a case study of Melbourne in 2016 and 2021, in the same manner
in which \citet{currie2010identifying} reported Melbourne in 2006. A
motivation for this study was to explore how this has changed. The share
of the population living in areas with Zero Transport Supply grew from
2.5\% (85,423 residents) in 2006 to 2.9\% (131,619 residents) in 2016,
and then again to 3.8\% (186,829 residents) in 2021. Compared to the
8.2\% (276,739) of Melbourne residents having Very High needs but Low,
Very Low or Zero Transport Supply in 2006 reported by
\citet{currie2010identifying} this study found equivalents of 11.2\%
(502,680 residents) in 2016 and 11.2\% (301,743 residents) in 2021.
Overall the results might suggest that the situation is moving in the
wrong direction, at least in Greater Melbourne, and that outer suburbs
continue to be most affected.

The extent to which these findings about Melbourne can be confidently
generalised to other places is not yet fully answered. Fortunately, the
widespread availability of GTFS datasets means other cases can readily
be examined so as to better understand whether Melbourne is
representative, and exploring social needs-gaps in other Australian
cities is an immediate direction for future efforts associated with this
program of research. In the meantime, some caution may be needed prior
to assuming that shifts in Melbourne are representative of everywhere
else. The population growth between 2006 (3.4m) and 2021 (4.9m) may be
an outlier, although low-density development patterns typical in
Melbourne appear common elsewhere, suggesting that the study's findings
about continued gaps in outer areas are likely generalisable. Melbourne
might also be an outlier as far as the share of government spending
going towards transport megaprojects\footnote{including: a new
  underground rail link through the CBD that is in the final stages of
  construction; a second major freeway crossing of the Yarra River to
  the west; and planning for the 90km-long Suburban Rail Loop.},
although it is unclear if this has led to lower spending than might
otherwise be the case on providing basic coverage for those who cannot
otherwise drive, or increasing service levels for those with the
greatest social need for transit.

As well as making comparisons of Melbourne across 2006, 2016 and 2021,
this paper has expanded on the analysis approach developed in
\citet{Currie2003Hobart}, \citet{Currie2004Gap},
\citet{Currie2007Identifying} and \citet{currie2010identifying}. The
mapping of changes in SI scores and how these changes relate to transit
routes and areas with large needs-gaps for a neighbourhood might be of
use to transport planners, advocates, politicians and other
decision-makers, and others seeking to build legitimacy for the
improvement or introduction of basic levels of transit.
\citet{delbosc2015impact} found that what transit was initially
implemented in the Selandra Estate provided a very important social
function and that there was a community desire for greater levels of
service. It is heartening that this area now has more routes and higher
service levels. However, Figure \ref{fig:Selandra_rise} shows that there
were similarly under-or-never-served communities nearby in 2021,
suggesting that the timely introduction of transit service to new
development areas continues to be a challenge in parts of Melbourne.
Further research might seek to confirm the extent to which similar
issues are evident in other parts of Melbourne and elsewhere.

Overall, the research reported in this paper may help practitioners and
decision-makers more easily identify gaps between the social need for
transport and the transit supplied. \citet{currie2010identifying}
suggested that using the Supply Index and needs-gap analysis techniques
would be much preferable to anecdotal or other informal inputs to
decision-making. The software package and analysis approaches reported
in this paper may allow the social needs-gap approach to be used more
easily and more widely so as to target new and improved services to
spatial areas and communities where there is the most need.

```

\bibliography{References.bib, packages.bib}


\end{document}
